### ISSUE TITLE
Add UI for re-ordering services

### ISSUE THREAD

**Issue by adamcooke** [adamcooke/staytus#1]

**Comment by notrab** [comment]
@adamcooke Can you explain a little more as to how you intended this to work? I wouldn't mind submitting a PR for such functionality.

**Comment by adamcooke** [comment]
The `Service` model has a field called position which is used to set the order that services are displayed in the interface. Unfortunately, this attribute isn't exposed anywhere.

I think I was just thinking of adding a simple JQuery UI sortable widget which would let you just drag and drop the order of services on the service list page. 

I'd pop a form around the whole table, put a hidden field  - `hidden_field_tag('order[]', service.id)` - on each table row and then automatically submit the form when the order was changed. A controller action will receive the `order` param array with the IDs in order and that can be passed to the model...

Finally, I would likely add a class method to `Service` called `reorder` which accepts an array of IDs in the which they should be displayed and update all the services with their new positions.

```ruby
def self.reorder(ids)
  ids.map(&:to_i).each_with_index do |id, index|
    service = Service.find(id)
    service.update(:position => index + 1)
  end
end
```

**Comment by notrab** [comment]
👍I was thinking the same. I'll try and submit this unless you or anyone else beats me to it.

**Comment by pgnuta** [comment]
Did this get anywhere?  Looks like it went dead but i think its an important feature so that messing with the database in the background is not required.

**Comment by sodul** [comment]
+1 on the feature, it looks like the internals already allow for this to work so it would be a nice to have.

**Comment by benjisoft** [comment]
+1

**Comment by marchenkov** [comment]
Any news about reorder? I need sorting inside "service group". How I can do this?
