### ISSUE TITLE
Add subscribers via Admin screen

### ISSUE THREAD

**Issue by infectious** [adamcooke/staytus#10]
Would be nice to be able to add subscribers directly here: https://status.impressiondesk.com/admin/subscribers

We're using this internally and adding people directly is more reliable than asking them to all go and subscribe.

**Comment by prolix21** [comment]
I'll second this request. Being able to manually enroll people would be nice. 

We are working on setting this up Staytus to better share information about network/service status and maintenance notices - http://status.3z.net/
