### ISSUE TITLE
Viaduct Discontinuing SMTP Support

### ISSUE THREAD

**Issue by leesalminen** [adamcooke/staytus#110]
http://email.viaduct.io/t/ViewEmail/y/0131D486B8B3EB44/C96542D190B98A5A4BD7C9066BE4161D

Viaduct will be discontinuing SMTP support in favor of a new mailing service called AppMail.

**Comment by adamcooke** [comment]
This shouldn't be an issue. The `STAYTUS_SMTP_HOSTNAME`, `STAYTUS_SMTP_USERNAME` and `STAYTUS_SMTP_PASSWORD` can simply be updated to new SMTP credentials from AppMail 😄
