### ISSUE TITLE
Help wanted, incorrect generate urls

### ISSUE THREAD

**Issue by PotatoQuality** [adamcooke/staytus#111]
Hi,

I  have some problems with a new settup.  
The problem i miss a ":" in the url. 

So basically, every url in the default emails notifcations is failing beceause the url is not correct.

I set the domain on in the setting page status.plexitnow.net
![image](https://cloud.githubusercontent.com/assets/2944704/20114853/4aacef44-a5f6-11e6-92d4-913bf1a22b6c.png)

**Comment by adamcooke** [comment]
E-Mail templates are written in the application. What does a template look like?
