### ISSUE TITLE
Help with the API

### ISSUE THREAD

**Issue by steviecoaster** [adamcooke/staytus#112]
I'm trying to leverage Invoke-RESTMethod in Powershell to query our Staytus server, but I'm getting a parameter error message in the response. 

Can someone point me in the direction of a properly formatted URL call? I'm missing something somewhere, and the API documentation is kind of lack luster.

$headers = New-Object "System.Collections.Generic.Dictionary[[string],[string]]"
$headers.Add("X-Auth-Token",$token)
$headers.Add("X-Auth-Secret",$secret)

$response = Invoke-RestMethod 'http://status.tusc.kent.edu:5000/api/v1/services/info/wireless' -Headers $headers

$response.data

message                                       
-------                                       
`service` parameter is required but is missing

I've tried several iterations of the URL, but nothing seems to want to work. Any help would be greatly appreciated.

**Comment by adamcooke** [comment]
You need to send the service parameter as JSON in the body of the request. I have no expeirence with PowerShell so can't help really. You'll need to ensure the request body looks like the below and you set the `Content-Type` header to `application/json`.

```javascript
{"service":"service_name"}
````

**Comment by steviecoaster** [comment]
That's actually quite helpful. I think I can run with that!
