### ISSUE TITLE
Last Updated showing incorrectly

### ISSUE THREAD

**Issue by hallr7** [adamcooke/staytus#115]
With an active issue, the "Last Updated" on the home page and issue history page show the time since created and not since last update.  Is this happening to everyone or just me?
![capturfiles_1](https://cloud.githubusercontent.com/assets/22135779/20369763/d4aa7b52-ac28-11e6-83fc-c9aff1338d6f.jpg)

**Comment by maueliass** [comment]
Same here.

Regards,

![x](https://cloud.githubusercontent.com/assets/14004699/20432669/6e733b16-ad87-11e6-8c96-fdff77b569da.png)

**Comment by adamcooke** [comment]
Thanks for reporting this. This is now fixed in master.
