### ISSUE TITLE
issues api "invalid-controller-or-action"

### ISSUE THREAD

**Issue by rosscdh** [adamcooke/staytus#116]
Hey there, great app simple to get running; thanks :)

found a small issue running: commit: `7efef42` stable branch (runs fine in master)

```
http http://:host/api/v1/issues/all X-Auth-Token:':key' X-Auth-Secret:':secret'

HTTP/1.1 400 Bad Request
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Date: Wed, 23 Nov 2016 03:12:37 GMT
Server: nginx/1.4.6 (Ubuntu)
Transfer-Encoding: chunked
X-Request-Id: abc2aa17-f65d-4a18-8f67-6cb30493e5c5
X-Runtime: 0.000923

{
    "status": "invalid-controller-or-action"
}
```

Manually created an issue thinking it was to do with needing an issue in the system... but no joy.

**Comment by adamcooke** [comment]
You don't seem to be sending the authentication headers. It looks like you're just sending them in the URL which is why you're getting this error. It's probably looking for an action called `all X-Auth-Token:':key' X-Auth-Secret:':secret'`

**Comment by rosscdh** [comment]
no thats: https://httpie.org its like curl but on steroids :)
