### ISSUE TITLE
Available clients

### ISSUE THREAD

**Issue by igorissen** [adamcooke/staytus#12]
Is there a list of available clients which use your API ?

**Comment by adamcooke** [comment]
What sort of thing are you looking to do?

**Comment by igorissen** [comment]
A client which update each x seconds (or minutes, hours) the status of our API is one example. It's possible to have also a client which update a graph of average response time of our API.

**Comment by prolix21** [comment]
I wonder if a better route is building some sort of integration between Staytus and something like PRTG (which has an API). There isn't much that PRTG can't monitor/probe/query. Let that do all the heavy lifting and then use Staytus to turn it into something public facing.

**Comment by adamcooke** [comment]
Once the Staytus API is fully functional, you'll be able to write any integration you want to update it using external data.
