### ISSUE TITLE
Email Link Didn't Change

### ISSUE THREAD

**Issue by ACBobby** [adamcooke/staytus#120]
I originally had the site URL set to subdomain.website.com, however, I changed it to website:5000 instead. Now, emails sent out still link to the old URL. I can't find any way to change this URL aside from the settings and I'm not sure why the mail template still uses the old URL.

**Comment by dgillard** [comment]
I've just taken a look at this on my local install. I've been able to make this change and restart the foreman server and get it to send using the new domain (and port). Although the change saved the domain change doesn't occur until the restart.

If that doesn't help you 

1) What is showing in the domain field on the settings page?
2) Are you using a custom email template?

**Comment by ACBobby** [comment]
Ah so the restart has to be done. Got it! I didn't actually know that so I never did the restart. I'll do that now, thanks!
