### ISSUE TITLE
Slack Integration 

### ISSUE THREAD

**Issue by tavisca-syedave** [adamcooke/staytus#126]
Can we add support slack tool integration

**Comment by adamcooke** [comment]
You may

**Comment by freibuis** [comment]
@adamcooke is there any plans to create a plugin framework so we can add features like this with out break future roadmap?

**Comment by rlunardelli** [comment]
Has this been implemented?

**Comment by peelman** [comment]
I will be adding a simplified Slack notification piece in the coming days/weeks.  I started down a path that was going to be far more complicated than really necessary I think.  So i'm just going to punt and clone/tweak the Email model to suit.  I figure that with Attachments, it should be pretty easy to get a decent looking slack message without a lot of work.

What i'm shooting for will be as simple one-or-nothing approach; if you choose to notify subscribers, it'll also send to the configured slack webhook (which, again, punting here, will be in the `environment.yml`), using the channel, username, icon, etc. also defined via ENV parameters.

Perhaps down the road we can add actual settings that can be configured from the WebUI, or associate specific channels to specific services somehow; but for now, I personally just need it working so I'm going to carve out the time to make it work in the most simplistic way that accomplishes what we need.  There's always time to make it fancy later.

**Comment by melsom** [comment]
Hello, any update here? Would love a Slack integration.

**Comment by JonathanPaluch** [comment]
Any update?

**Comment by peelman** [comment]
we ended up deploying Hund. Staytus just didn’t offer enough and was going to require enough dev and upkeep that the $29/mo for Hund was a net win. so i won’t be adding the integration i proposed, at least not anytime in the foreseeable future.
