### ISSUE TITLE
Api to create/update incidents

### ISSUE THREAD

**Issue by vikramgorla** [adamcooke/staytus#13]
are you planning to implement API to create/update incidents.
It would be really useful to have it so that twe can have alert integration with monitoring systems (new alrert, alert resolution, update, etc,...)

**Comment by adamcooke** [comment]
At the moment the API doesn't support adding incidents but it certainly can do. I'll look at adding this!

**Comment by vikramgorla** [comment]
Thanks a lot Adam, that would be great.
My use case would be to integrate staytus with multiple monitoring/alerting systems to give clear and automated visibility on ongoing incidents.

I will work on plugins for munin, keynote, etc,.. once the api is ready

**Comment by glaszig** [comment]
:+1:

**Comment by glaszig** [comment]
i have this working, i think. @adamcooke, still there? want pr?

**Comment by dloomer** [comment]
@glaszig I'm not Adam, but I'd love to try your code. I don't see a fork on your github account; could you push it up?

**Comment by glaszig** [comment]
@dloomer [there](https://github.com/adamcooke/staytus/compare/master...glaszig:api/issue-creation) you go.

**Comment by dloomer** [comment]
Thanks @glaszig! I will give it a shot.

**Comment by dloomer** [comment]
Thanks @glaszig - this works great. For your use case, do you have a need to also update/resolve issues through the API?

**Comment by glaszig** [comment]
yes, i'm working on this. will continue next week.

**Comment by glaszig** [comment]
pushed a commit that enables posting issue updates. only integration-tested, let me know if it's shit ;)

**Comment by glaszig** [comment]
@dloomer i'd be happy about your input in #27 if you like.

**Comment by tilsammans** [comment]
I believe this can be closed @adamcooke as this was merged with #27
