### ISSUE TITLE
Issue history listing in chronological order

### ISSUE THREAD

**Issue by rniedosmialek** [adamcooke/staytus#131]
Is there plans to include a chronological history listing for issues so users can browse and view past issues for reference to incidents that may come up in later review.

**Comment by adamcooke** [comment]
There is a history at the bottom of the page. Is that what you mean?

https://demo.staytus.co/history

**Comment by robert7811** [comment]
It is similar to what I was thinking about. If the summary of this view could be present on the home page under the status block area possibly listing only the last 7 issues reported and then a link to the full history if the user needs to go deeper I think would help make the history feature pop more. I am just think of from a captain obvious view as I spent a half hour of testing before I realized the link was there. This is just a suggestion as this may be just me.

Great status app! Tried quite a few others but this one is a sure shot winner for quick, easy to setup and does what it is supposed to.

Not to get off the subject but do you have a recommendation on the best startup service approach is for Staytus? I was thinking along the lines of Supervisor.
