### ISSUE TITLE
Public and Private Staytus setup on alternate ports

### ISSUE THREAD

**Issue by rniedosmialek** [adamcooke/staytus#133]
I would like to setup a public facing Staytus and a private for internal status dashboard. Staytus by default runs from port 5000 thousand but where is this defined so that I may change it to an alternate port to create the private version?

**Comment by benjisoft** [comment]
+1

**Comment by dgillard** [comment]
If you are running it using Foreman you could try the following to run it on port 3000

`bundle exec foreman start -p 3000`
