### ISSUE TITLE
How - SMTP & gmail?

### ISSUE THREAD

**Issue by MikkelDK** [adamcooke/staytus#137]
Hello.

How to setup SMTP with gmail?

Since there is no way to add "SSL or TLS" so. what to do?

**Comment by adamcooke** [comment]
I have added support for using starttls and getting the auth mode. These changes are in the master branch.

* `STAYTUS_SMTP_PORT=587` will set the port
* `STAYTUS_SMTP_STARTTLS=1` will enable auto starttls
* `STAYTUS_SMTP_AUTH_MODE` will allow you to change the way passwords are sent. You shouldn't need to change this for Google.
