### ISSUE TITLE
Emails not send

### ISSUE THREAD

**Issue by Vialaxy** [adamcooke/staytus#14]
Hello,

I've successfully set up the app ( wich is pretty nice :P ) but i have a problem with mails, even after set up general settings i never receive them.

If i remember well the first time  it sayed something like " you haven't configured the smtp server so the mails will be send throught the  php sender" but now i doesn't say anything.

So how can i configure the smtp server ?

Kind regards,
Vialaxy

**Comment by adamcooke** [comment]
E-mails are sent using sendmail if you haven't configured an SMTP server. To configure an SMTP server, you need to set the following environment variables.

* `STAYTUS_SMTP_HOSTNAME`
* `STAYTUS_SMTP_USERNAME`
* `STAYTUS_SMTP_PASSWORD`

**Comment by Vialaxy** [comment]
@adamcooke  can you tell me how to set up the env ?

Sorry but i'm a bit new to linux ^^

**Comment by adamcooke** [comment]
Not without knowing more about your environment no. Google should be able to help, though.

https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps

**Comment by Vialaxy** [comment]
@adamcooke  thanks i've succesfully added the variables with the right  values but still doesn't work

PS:  I use a custom domain name to send email
