### ISSUE TITLE
Translation of frontend only?

### ISSUE THREAD

**Issue by Shyru** [adamcooke/staytus#144]
We would like to use staytus for a german status page. I already saw issue #56 but would like to extend that question. As already in the title we would only translate the frontend, not the admin interface.

I already saw the file [content/locales/en.yml]( https://github.com/adamcooke/staytus/blob/master/content/locales/en.yml) that allows to override **some** texts used in the frontend. What is the plan with this file? Should it be possible to override all frontend-texts in the future? Would you accept a pull-request that makes all the strings used in the frontend templates translatable via that locale-file system? Or are there other sources where frontend-visible texts originate from?
If you would not accept a pull, should we fork your repository and translate the frontend templates in our fork and manually update the fork from your repo over time to get new features?

**Comment by Shinoku1987** [comment]
can somebody provide how this file even works?
