### ISSUE TITLE
Staytus on Viaduct - Worker Process 

### ISSUE THREAD

**Issue by brianjking** [adamcooke/staytus#15]
Hello,

I've deployed Staytus on your Viaduct platform and am finding it quite enjoyable -- congrats and great job. However, I do have a question regarding the two different web & worker processes.

As of right now I'm simply using the free tier of Viaduct and have set the "worker" process to 0 for "bundle exec rake jobs:work" and everything appears to be functioning correctly.

Can you please advise on what functionality I'm missing by setting this to have 0 processes to remain on the free tier for the time being?

Thanks!

![screenshot6-12-1509 45](https://cloud.githubusercontent.com/assets/6786817/8131408/13a406f8-10e8-11e5-93db-98d01458631e.png)

**Comment by adamcooke** [comment]
The worker is used for sending all notification emails at the moment. In the future, it will also be used to communicate with other third party services. You don't strictly need it but you should disable notifications for now.
