### ISSUE TITLE
where to remove unsubscribe footer?

### ISSUE THREAD

**Issue by fone** [adamcooke/staytus#153]
I am using staytus to broadcast maintenance notifications internally only.

can you tell me where in the config I can edit out the unsubscribe footer, as I don't want a random employee to unsubscribe everyone from these emails.

thanks

**Comment by freibuis** [comment]
I do not believe there is any.

but you could copy the default theme and just css the button out or just remove it.. ;) it is open source after all

**Comment by fone** [comment]
Ah well if it's in the them files I can find it.
Thanks!

**Comment by freibuis** [comment]
should be able to change it here 
https://github.com/adamcooke/staytus/blob/master/content/themes/default/views/pages/subscriber_verification.html.erb

I would copy the default theme then mod that.... that way if master branch gets change you will not loose any changes

**Comment by robertlyall** [comment]
If you search this repository for "unsub" and "unsubscribe" it should be very obvious what you need to remove.

**Comment by fone** [comment]
Yeah what I was looking for was in /themes/default/email.html
