### ISSUE TITLE
API Status Monitoring

### ISSUE THREAD

**Issue by submah** [adamcooke/staytus#156]
Hello,

I have installed the Staytus tool in my local linux box. I ma getting the Dashboard. My vision is to monitor few customers API's with staytus tool. 
Could you please guide me how can i send the API status result to the staytus dashboard?

Thank You,
Subrat

**Comment by Rulasmur** [comment]
Hi @submah to integrate Staytus with other tools, you would need an application monitoring the health of the API and then a custom integration/app to update Staytus when there are issues. Staytus does not pull data, so you have to push updates to it.

> My vision is to monitor few customers API's with staytus tool.
An application such as Icinga2 would probably be more suited to what you are trying to achieve.
