### ISSUE TITLE
How can I auto-start Staytus on boot?

### ISSUE THREAD

**Issue by ciph** [adamcooke/staytus#157]
I want Staytus to automatically start after a reboot/power failure etc. Right now I have to run the command "procodile start" manualy to start the service.

I have tried to do a simple script and put it in crontab, but it doesnt work. Can anyone provide me with a working solution?

This is what I put in a script.sh file
cd /opt/staytus
procodile start

**Comment by edo660** [comment]
how about this (for systemd, /etc/systemd/system/staytus.service)? Haven't tested whether it starts on boot or anything just yet, but service staytus start/stop works (ubuntu 16.04 LTS)

```
[Unit]
Description=Procodile-Staytus
After=network.target

[Service]
Type=forking
KillMode=none

ExecStart=/usr/local/bin/procodile start --root /opt/staytus/staytus/
ExecStop=/usr/local/bin/procodile stop -s --wait --root /opt/staytus/staytus/

User=staytus
Group=staytus

[Install]
WantedBy=multi-user.target
```

**Comment by ciph** [comment]
Thank you so much its working! :)
Im running Ubuntu and I did below:

`vi /etc/systemd/system/staytus.service`

```
[Unit]
Description=Procodile-Staytus
After=network.target

[Service]
Type=forking
KillMode=none

ExecStart=/usr/local/bin/procodile start --root /opt/staytus/
ExecStop=/usr/local/bin/procodile stop -s --wait --root /opt/staytus/

User=root
Group=root

[Install]

WantedBy=multi-user.target
```

Above will make it possible to run start/stop and below will automatically start the service on boot :)

`systemctl enable staytus.service`
