### ISSUE TITLE
No API integration for scheduled maintenance

### ISSUE THREAD

**Issue by Silarn** [adamcooke/staytus#159]
My team was hoping to integrate with the API to automatically create issues when downtime was detected - however we'd obviously like to skip this during scheduled maintenance.

However, the current APIs don't seem to be integrated with the maintenance features.

**Comment by fgierlinger** [comment]
+1

I just noticed the exact same behaviour. This is a real bummer since we're trying to automatically set the status of our interfaces and during a scheduled maintenance all potential issues should be ignored.
