### ISSUE TITLE
Adding URLs as links to status updates & components

### ISSUE THREAD

**Issue by brianjking** [adamcooke/staytus#16]
Hello,

Is there a way to add URLs as hyperlinks to Staytus's "Post a new message" areas? If so, what's the syntax for doing so?

Secondly, is there a way to have the main site link to the components URL at this time?

Thanks!

**Comment by adamcooke** [comment]
At the moment, there's no way to insert any special text into the updates. I plan to add markdown support at some point though at which point you will be able to do this. 

I'm not sure I understand your second question

**Comment by brianjking** [comment]
My second comment is I'd like to have a component link to the components URL if a user clicks on it. For example: If someone clicked on "dockdogs website" when it's "Operational" that they would link out to http://dockdogs.com.

![screenshot6-15-1516 18](https://cloud.githubusercontent.com/assets/6786817/8169827/2442d770-137a-11e5-8a01-afad0b51620b.png)
