### ISSUE TITLE
500 error when adding subscriber email address on public page

### ISSUE THREAD

**Issue by acorkin** [adamcooke/staytus#161]
If a subscriber attempts to add their email address, they are presented with a 500 error, no email is sent. (http://status.radio.co/subscribe/email)

However if an admin verifies them, they will receive emails for incident updates etc. 

Production log:

> D, [2017-06-13T15:05:21.073775 #23762] DEBUG -- : [0d9e4694-e440-4d99-87ed-16d67fceadb8]   SQL (0.9ms)  INSERT INTO `subscribers` (`email_address`, `verification_token`, `created_at`, `updated_at`) VALUES ('example@email.com', '1da5b9ef-9d4d-4a25-89b5-e6c816ed0c1d', '2017-06-13 15:05:21', '2017-06-13 15:05:21')
> D, [2017-06-13T15:05:21.077187 #23762] DEBUG -- : [0d9e4694-e440-4d99-87ed-16d67fceadb8]    (1.8ms)  COMMIT
> I, [2017-06-13T15:05:21.091558 #23762]  INFO -- : [0d9e4694-e440-4d99-87ed-16d67fceadb8] Completed 500 Internal Server Error in 64ms (ActiveRecord: 11.1ms)
> F, [2017-06-13T15:05:21.094304 #23762] FATAL -- : [0d9e4694-e440-4d99-87ed-16d67fceadb8]   
> F, [2017-06-13T15:05:21.094811 #23762] FATAL -- : [0d9e4694-e440-4d99-87ed-16d67fceadb8] NameError (uninitialized constant Staytus::Email
> Did you mean?  Premailer
>                Mail):
> F, [2017-06-13T15:05:21.095025 #23762] FATAL -- : [0d9e4694-e440-4d99-87ed-16d67fceadb8]   
> F, [2017-06-13T15:05:21.095259 #23762] FATAL -- : [0d9e4694-e440-4d99-87ed-16d67fceadb8] app/models/subscriber.rb:41:in `send_verification_email'
> [0d9e4694-e440-4d99-87ed-16d67fceadb8] app/controllers/pages_controller.rb:59:in `subscribe_by_email'

Web.log:

> 81.134.80.112 - - [13/Jun/2017:15:15:40 +0000] "GET /subscribe HTTP/1.0" 200 - 0.0130
> 81.134.80.112 - - [13/Jun/2017:15:15:49 +0000] "POST /500 HTTP/1.0" 500 1477 0.0329

Ruby: ruby 2.3.4p301 (2017-03-30 revision 58214) [i686-linux]
Rails: 5.1.1

**Comment by freibuis** [comment]
use the stable branch email is broken on master. I think this is the same issue #160  is having

**Comment by acorkin** [comment]
Resolved in issue #150. Closed.
