### ISSUE TITLE
RSS and JSON Feeds for History

### ISSUE THREAD

**Issue by davidwkeith** [adamcooke/staytus#162]
Having a RSS or JSON Feed for /history would be nice. Allows simple subscriptions for downstream services.

**Comment by freibuis** [comment]
So I have looked through this code and this would be possible but would open a possible secruity issues to add it to the main project....  but what I would do would be drop `history.json.jbuilder` file into `content/themes/default/views/pages` directory (change the directory `default` if custom theme is used


add this to it
```ruby
json.extract! history_item, :id, :item_type, :item_id, :date
json.url history_url(history, format: :json)
```


Not sure if this would be beneficial to this project so I wont create a merge request until ok'd

**Comment by norphus** [comment]
I've probably missed something here but I've created a file in the folder @freibuis mentioned called history.json.jbuilder and copied his code snippet into it. When I try to browse `http://url/history.json`, I get 
`{"status":406,"error":"Not Acceptable"}`

Any ideas? Thankyou
