### ISSUE TITLE
Can Staytus be fully integrated with Zabbix?

### ISSUE THREAD

**Issue by nan008** [adamcooke/staytus#169]
Hello,

We started evaluating status pages and were looking at Cachet, our monitoring system is run by Zabbix and the problem with Cachet is that apparently you cannot send some of the status metrics to it. We have web scenarios that we want to display in the status page, is that possible with Staytus?

**Comment by shiyunjin** [comment]
你可以尝试 https://github.com/shiyunjin/zabbix-cachet-metrics 这是我刚写的方案
