### ISSUE TITLE
Search in service group

### ISSUE THREAD

**Issue by andamasov** [adamcooke/staytus#170]
Hello,
we looking to implement search inside service group
Use case:
We have service group with service areas (by zip code)
instead of show all areas we want to show search box where the user can look up by zipcode
maybe we can show areas with warning below the search box 
All comments welcome

**Comment by freibuis** [comment]
I think this is a good idea and I added this to my deployment.

I have created a pr #171  

ok this is not a search function... but an endpoint. you could add search functionality on it
for example
```
http://server/service-group/:groupname
```
example
```
http://server/service-group/group-1
http://server/service-group/group-two
```
