### ISSUE TITLE
404 on docker hosted instance

### ISSUE THREAD

**Issue by bendehghan** [adamcooke/staytus#173]
Hi guys,

I have staytus running in a docker container: 

`docker run -d -p 80:5000 --name stayus adamcooke/staytus --restart always
`

When I run the server for a while (like hours), I start getting 404 on default.css and default.js after it worked perfectly well initially. This goes away if I stop and restart the docker container. So a restart will make it work well again.

What's going on here?

Thanks,
Ben

**Comment by freibuis** [comment]
can you give some samples of the debug log?

does this happen in production or development?

**Comment by bendehghan** [comment]
I'm not sure what debug logs you're referring to. The docker logs tail is like this:

`23:25:50 web.1    | started with pid 545
23:25:50 worker.1 | started with pid 546
23:25:58 web.1    | => Booting Puma
23:25:58 web.1    | => Rails 4.2.4 application starting in production on http://0.0.0.0:5000
23:25:58 web.1    | => Run `rails server -h` for more startup options
23:25:58 web.1    | => Ctrl-C to shutdown server
23:25:58 worker.1 | => You haven't configured an SMTP server. Mail will be sent using sendmail.
23:25:59 web.1    | => You haven't configured an SMTP server. Mail will be sent using sendmail.
23:25:59 worker.1 | [Worker(host:f1e9767b8049 pid:546)] Starting job worker
23:25:59 web.1    | Puma 2.11.1 starting...
23:25:59 web.1    | * Min threads: 0, max threads: 16
23:25:59 web.1    | * Environment: production
23:25:59 web.1    | * Listening on tcp://0.0.0.0:5000
`

further up the logs I see 

`I, [2017-07-25T23:25:41.002121 #442]  INFO -- : Removed /opt/staytus/public/assets
rm -rf /opt/staytus/tmp/cache/assets
`

**Comment by freibuis** [comment]
could you take a sample of the logs that shows the default.css 404'ing?

**Comment by bendehghan** [comment]
I found this in the logs:

> I, [2017-07-25T21:42:54.333538 #535]  INFO -- : [69469d9c-0864-4b0d-a4f7-68dece7
> 88f57] Started GET "/javascripts/default.js" for 98.232.114.111 at 2017-07-25 21
> :42:54 +0000
> F, [2017-07-25T21:42:54.336807 #535] FATAL -- : [69469d9c-0864-4b0d-a4f7-68dece7
> 88f57] 
> ActionController::RoutingError (No route matches [GET] "/javascripts/default.js"
> ):

A grep on "Error" gives a lot of RoutingError messages for all sorts of /db or /php or some other requests that seem to be be bots or phishing. Anyway, but the default.css and default.js errors are the ones I saw in the browser and then in the logs.
