### ISSUE TITLE
Heroku Button

### ISSUE THREAD

**Issue by marceloboeira** [adamcooke/staytus#180]
Since the service is very decoupled from the rest of the infrastructure, it could be nice to be able to start an instance on Heroku (isolated infra) to monitor.

More info at:
https://blog.heroku.com/heroku-button
https://devcenter.heroku.com/articles/heroku-button

**Comment by jbrooksuk** [comment]
Personally, I'd never do this again... https://james-brooks.uk/deploy-to-heroku-buttons/

**Comment by freibuis** [comment]
heroku for me is all about disconnection... its not on our infrastructure... its dirt cheap (zero cost if you are having no issues lol)

**Comment by jbrooksuk** [comment]
On the free tier, you don't (at least didn't get 24/7 availability) which defeats the purpose of a status page...

**Comment by marceloboeira** [comment]
> its not on our infrastructure

In general, I don't find a good practice to monitor your infra using your own infra...

**Comment by marceloboeira** [comment]
> On the free tier, you don't (at least didn't get 24/7 availability) which defeats the purpose of a status page...

You get 1000 hours per month on the free tier. Which is much more than you need to monitor another app...

**Comment by freibuis** [comment]
the only problem with the free tier is the worker (for email) will not work..
so if you dont want to pay for a status page and you hardly ever have any outages it will cost you nothing....   just pay when you have an issue... its only 7$. boom

**Comment by marceloboeira** [comment]
@freibuis the free tier allows you to use multiple processes now. I have one app running on free tier with sidekiq.

**Comment by freibuis** [comment]
@marceloboeira wow. didnt know.... 🤔 this could be dangerous :)

**Comment by ideasasylum** [comment]
@marceloboeira [Here's a fork](https://github.com/ideasasylum/staytus) I hacked together that's deployable using the Heroku button. You can see [the PR for more details](https://github.com/adamcooke/staytus/pull/240) in what I needed to change
