### ISSUE TITLE
therubyracer instead of node.js

### ISSUE THREAD

**Issue by zrhpwr** [adamcooke/staytus#181]
Hi
Question:
As I don't have node.js available on my hosting service I'd like to ask if it's possible to use the gem "therubyracer" as Javascript Interpreter.

Best regards,

**Comment by freibuis** [comment]
just fork the project and make the changes....   therubyracer gem is problematic as it doesn't compile on all o/s's. most ppl I work with use sass over less because of rails 5 defaulting to sass

**Comment by ocha** [comment]
@donatt also, if you still plan to use rubyracer, I highly recommend trying https://github.com/discourse/mini_racer . It should be enough for asset compilation is much more lightweight.
