### ISSUE TITLE
Running staytus automatically on system start with notifications process

### ISSUE THREAD

**Issue by martycarloss** [adamcooke/staytus#183]
Hello!

I've installed staytus and started playing around with it and I like what you have done so far, it looks great! I am completely unfamiliar with Ruby and how it works, so my question is this: what is the best way to run staytus in the background and have the notification workers run in the background. I've read the documentation as far as procodile and also running it as a foreground process, but I'm not clear on how to do it all properly. How would I set this up so that staytus and the notification workers would run automatically after a server reboot? Thanks in advance for your time!

**Comment by martycarloss** [comment]
So by playing around I see that using 'procodile start --foreground' runs the server and background jobs fine... so what is the best method to make sure this starts when my server starts?

**Comment by JamesrenaudMitel** [comment]
See #157 

This worked great for me.
