### ISSUE TITLE
Testing the API

### ISSUE THREAD

**Issue by ferztyle** [adamcooke/staytus#184]
Hi, im trying to use the api sending this line via curl : curl mystaytus.domain.com:5000/api/v1/issues/all but im getting this error : "Invalid API credentials provided". It is something in my configuration tha i am missing maybe? Since i have no backgrounds en ruby, can you provide me some examples using the api via curl command?.

**Comment by JamesrenaudMitel** [comment]
You need to sign into your Staytus page and issue a token and secret, then pass those as part of the header of your request.
