### ISSUE TITLE
Ruby Error - 01.09.2017

### ISSUE THREAD

**Issue by Benni9323** [adamcooke/staytus#185]
```
root@ventix:/opt/staytus/staytus# sudo -u staytus bundle install --deployment --without development:test
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
activesupport-5.1.1 requires ruby version >= 2.2.2, which is incompatible with the current version, ruby 2.1.5p273
root@ventix:/opt/staytus/staytus#

```

**Comment by Rulasmur** [comment]
@Ventix you need to update your ruby(possibly manually installing it)
Needs to be minimum 2.2.2 and your currently installed version is 2.1.5
`activesupport-5.1.1 requires ruby version >= 2.2.2, which is incompatible with the current version, ruby 2.1.5p273`

**Comment by Ventix** [comment]
@Rulasmur But how? I have the 2.3 and its doesn't works!

**Comment by kishoreyellamraju** [comment]
@Ventix  I had the same error. If you have multiple versions of ruby installed on your server then make sure that your bundler is using the right version of ruby (>=2.2.2). I uninstalled and re-installed bundler to use the ruby version 2.2.2 and that fixed the issue for me.

$ bundler env

## Environment

```
Bundler   1.15.4
Rubygems  2.4.5.2
**Ruby      2.2.7p470 (2017-03-28 revision 58194) [x86_64-linux-gnu]**
Git       1.9.1
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.1f 6 Jan 2014
```
