### ISSUE TITLE
History/Resolved issues not working

### ISSUE THREAD

**Issue by martchoice** [adamcooke/staytus#186]
Hi,

I'm getting this error when I try to check the history/resolved issues:

"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

There are the logs I got when I try to access the page:

- - [20/Sep/2017:09:40:24 -0400] "GET /500 HTTP/1.1" 500 1477 0.0318
- - [20/Sep/2017:09:40:24 -0400] "GET /favicon.ico HTTP/1.1" 304 - 0.0004
- - [20/Sep/2017:09:45:59 -0400] "GET /500 HTTP/1.1" 500 1477 0.0394
- - [20/Sep/2017:09:46:00 -0400] "GET /favicon.ico HTTP/1.1" 200 - 0.0040
- - [20/Sep/2017:09:46:10 -0400] "GET /500 HTTP/1.1" 500 1477 0.0343
- - [20/Sep/2017:09:46:11 -0400] "GET /favicon.ico HTTP/1.1" 200 - 0.0008
- - [20/Sep/2017:09:46:14 -0400] "GET /500 HTTP/1.1" 500 1477 0.0374
- - [20/Sep/2017:09:46:14 -0400] "GET /favicon.ico HTTP/1.1" 200 - 0.0017

Everything was fine, but after a couple of issues, it stops working. I got 2 different servers using staytus, and I'm having the same issue.

Any idea?

**Comment by skynojoke** [comment]
I'm having this issue as well

**Comment by martchoice** [comment]
Is this project dead?

**Comment by skynojoke** [comment]
I sure hope not! I'm loving this project. I currently use it in my internal IT department for notifying users.
