### ISSUE TITLE
Incident management

### ISSUE THREAD

**Issue by teolupus** [adamcooke/staytus#189]
Hi Adam,

Excellent work on this project!

Would you be interested in a contribution that introduces service level management capabilities to Staytus?

Here are the user stories I have in mind:

1. As a system administrator, I want to store the start and end date of an incident, so that I know for how long it affected my service and generate service level reports.

2. As a system administrator, I want to write notes against an incident, so that I can document its description, impact and root cause.

3. As a user of the status page, I want to see service level graphs for each service, so that I can know the historical service levels provided.

A suggestion for the implementation plan:

- Introduce a new configuration option called "service_level_management" and set the default to false. If enabled a new panel would be added to the admin section called "incidents" and a new menu called "Service Levels" to the status page.

- Add a new table to the data model called "incidents" with a one to one relationship with issues. The new table introduces the following attributes: started_at (t.datetime), ended_at (t.datetime), description (t.text), impact (t.text), cause (t.text), cause_known (t.boolean), cause_removed (t.boolean).

- The "incidents" panel allows system administrators to:
-- Store/adjust the actual start and end time of an incident, as opposed to the datetime the notification was created/updated on the status page.
-- Document the description of the incident (what happened), the impact (who was affected and how) and the its cause.
-- Perform problem management, by marking incidents with a known root cause and root cause removed (when a permanent fix has been applied).

- Add a "Service Levels" entry to the menu at the bottom (by the side of "History"). When users click on service levels, they will be able to see historical service level graphs for each service, showing the state of the service over time.

What are your thoughts about it?

**Comment by fone** [comment]
As a user, I would love to see this feature added. I can tell you it'd get a lot of use!

**Comment by rlunardelli** [comment]
+1

**Comment by teolupus** [comment]
@adamcooke : what do you think about the proposed change? Do you agree with the proposed implementation?
