### ISSUE TITLE
notify groups

### ISSUE THREAD

**Issue by fone** [adamcooke/staytus#193]
this is more of a feature request.
I use staytus to send out company wide notifications for scheduled maintenance.

This is some maintenance that the entire company doesn't need to know about. In these cases it'd be good if I could direct who the notification goes to. At this time you can only check to send a notification out to subscribers.

It would be great if there could be a option to select a particular "group(s)" to send a notification to. Then in the panel you'd simply build this group, and all those email distros to those groups.

**Comment by asrob** [comment]
Yes, this feature would be awesome! :)

**Comment by adamcooke** [comment]
Sounds handy 👍
