### ISSUE TITLE
SMTP with TLS Send Fails 

### ISSUE THREAD

**Issue by jamesrenaud** [adamcooke/staytus#194]
I've got an SMTP server configured, running off master (so I have the latest initializers as in #160 ).

My worker log is indicating a failure to send:
[Worker(host:ip-172-31-31-156 pid:14671)] Job Issue#send_notifications (id=4) FAILED (0 prior attempts) with Net::SMTPAuthenticationError: 530 Must issue a STARTTLS command first

In theory by default the SMTP initializer should be using STARTTLS if its required, so I'm not sure why this is happening.

**Comment by JamesrenaudMitel** [comment]
@adamcooke any chance you have any thoughts on this?
