### ISSUE TITLE
Integrations with third party services

### ISSUE THREAD

**Issue by anarcat** [adamcooke/staytus#2]
it would be nice if this software could do notifications on other services.

otherwise this looks nice! good job!

**Comment by benjisoft** [comment]
+1

**Comment by robert7811** [comment]
+1 OpsGenie webhook would be nice along with AWS SNS

**Comment by chriseatworld** [comment]
+1

**Comment by splattner** [comment]
+1

**Comment by DevKyleS** [comment]
+1
