### ISSUE TITLE
Problem consuming the api

### ISSUE THREAD

**Issue by luizppduarte** [adamcooke/staytus#202]
Hello, 

I'm trying to obtain better details about determinated service and i dont having success, i'm using postman e doing this way

http://exemplo.com:5000/api/v1/services/info?service=api

Result: 

{
    "status": "parameter-error",
    "time": null,
    "flags": {},
    "data": {
        "message": "`service` parameter is required but is missing"
    }
}

I'm achieving to list all services and problems, but when i try to select some specific object the api return this error

How can i pass the parameters ?

I'm using 1.2.0 api version

Thanks for attention

**Comment by tmanternach** [comment]
I installed Postman and initially had the same result as you, but I figured it out!

You must have the X-Auth headers set correctly in Postman, so we'll skip that. Set your URL to `http://exemplo.com:5000/api/v1/services/info`. Then, find the section for "Body" in the same row as "Authorization", "Headers", "Pre-request Script", and "Tests". Once you are there, change the type to "raw" and then change the drop-down from "Text" to "JSON". In the text field, enter this JSON code:

`{ "service": "api" }`

That's it, it should work! Here is the curl equivalent: 

`curl -H "X-Auth-Token: TOKENHERE" -H "X-Auth-Secret: SECRETHERE" -H "Content-Type: application/json" -X POST -d '{"service":"api"}' http://exemplo.com:5000/api/v1/services/info`

Here's a screenshot of my Postman result. Good luck!

![screen shot 2018-01-18 at 7 50 23 am](https://user-images.githubusercontent.com/647920/35104517-49013ae2-fc26-11e7-867f-f77924fb3b82.png)

**Comment by deblum1995** [comment]
Hi @tmanternach 
can you explain how you have set the X-Auth Header correctly in Postman.

Thanks!

**Comment by tmanternach** [comment]
@deblum1995 I haven't used Staytus in a long time, so I can't actually test this. But re-reading this, I think this is how you need to set up the Headers tab in Postman: 
<img width="780" alt="screen shot 2019-02-08 at 7 14 16 am" src="https://user-images.githubusercontent.com/647920/52483510-5e020400-2b71-11e9-9f1b-5d166348250e.png">

Let me know if you need more help! Good luck.
