### ISSUE TITLE
Feature Request: Design Options

### ISSUE THREAD

**Issue by cprofitt** [adamcooke/staytus#206]
I would like to see some options for changing the header height and the background color in the WUI.

**Comment by uclnj** [comment]
It would be nice to have this as the only way to adjust the settings now is to make changes to the themes stylesheets and rebuild with a sudo bundle exec rake staytus:build followed by a reset of the process.  Doable but not friendly.

**Comment by md-vhb** [comment]
I'd like to have such a feature as well.
