### ISSUE TITLE
Duplicate Emails

### ISSUE THREAD

**Issue by sergioloera** [adamcooke/staytus#216]
I want to apologize in advance since there's no venue for noob's. With that said, I am running into duplicate emails. When I look in the log I see: 

`[Worker(host:XXXXXX pid:6474)] Job IssueUpdate#send_notifications (id=219) RUNNING
[Worker(host:XXXXXX pid:6474)] Job IssueUpdate#send_notifications (id=219) FAILED (12 prior attempts) with Net::OpenTimeout: execution expired
[Worker(host:XXXXXX pid:6474)] 1 jobs processed at 0.0328 j/s, 1 failed
[Worker(host:XXXXXX pid:6474)] Job IssueUpdate#send_notifications (id=220) RUNNING
[Worker(host:XXXXXX pid:6474)] Job IssueUpdate#send_notifications (id=220) FAILED (12 prior attempts) with Net::OpenTimeout: execution expired
[Worker(host:XXXXXX pid:6474)] 1 jobs processed at 0.0333 j/s, 1 failed
`
I've diabled ipv6 as some googlling pointed to that but hasn't resolved it. Any pointers?

**Comment by adamcooke** [comment]
Looks like the job is failing part way through sending an email and then being retried. Jobs actually shouldn't be retried in Staytus so i've pushed an update to stop that from happening. You still have an underlying issue to fix though.
