### ISSUE TITLE
[Feature Request] Visual graphic for Historical data for Downtime/Update/Maintenance/etc.

### ISSUE THREAD

**Issue by Sixiepoo** [adamcooke/staytus#219]
Not sure if already asked, would be nice to have a graph indicating the Downtimes &/or Uptime, etc.

or a way to show in graph or visual of the incidents as a historical graph, for example discord's status page.
https://status.discordapp.com/uptime

another thing is to have the ability to export all entered data into excel, having incidents, when they happened, when it was updated, etc.

**Comment by jeremyjhall** [comment]
This would be a great addition.

This is how uptime.io does it:

<img width="1039" alt="screen shot 2018-04-28 at 11 32 10 am" src="https://user-images.githubusercontent.com/1190351/39391549-d90f67d0-4ad7-11e8-9120-b8469e17cb96.png">

The dot could be colour coded depending on the type of issue. The tooltip could show the name of the affected service/s and link to the respective issue.
