### ISSUE TITLE
Auto Closing of Maintenance

### ISSUE THREAD

**Issue by Levi-11** [adamcooke/staytus#220]
Created a maintenance for a service with duration 30 minutes. Even after the maintenance period, the service is not operational. Created a service first and made it operational. Then scheduled a maintenance for the service. The scheduled time was 30 minutes. Even after the time, the maintenance was not closed, as I have expected. The version used is the current master. The browser used is Google Chrome version 64 in Ubuntu 16.04 mate.

**Comment by adamcooke** [comment]
This is intentional. The ability to provide a time window is for informational purposes only and maintenance should always be closed with a message.
