### ISSUE TITLE
Permalink field

### ISSUE THREAD

**Issue by StuartWalsh** [adamcooke/staytus#221]
The Permalink field in services. What should I enter there. when I try to add something it won't accept anything or returns 'already taken'

**Comment by Unthred** [comment]
I would like to know this too. I keep getting Permalink is invalid.

**Comment by as3k** [comment]
It looks like this is closed, but I'm having the same issue. There's no documentation that I could find as to what goes in this field. @adamcooke if you could help me out on that, I'd be super appreciative.
