### ISSUE TITLE
Upgrade fails on bundler command and Staytus is broken

### ISSUE THREAD

**Issue by rniedosmialek** [adamcooke/staytus#222]
I am in the process of updating our Staytus and receive the following error in the update process. 

"$ cd /opt/staytus/staytus
$ sudo -u staytus procodile stop -s --wait
$ sudo -u staytus git pull origin master
$ sudo -u staytus bundle
$ sudo -u staytus bundle exec rake staytus:build staytus:upgrade
$ sudo -u staytus procodile start"

"ubuntu@ip-10-1-5-158:/opt/staytus/config$ bundle exec rake staytus:build staytus:upgrade
(in /opt/staytus)
rake aborted!
TypeError: no implicit conversion of Fixnum into String
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config.rb:12:in `[]='
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config.rb:12:in `block in load'
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config.rb:11:in `each'
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config.rb:11:in `load'
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config/railtie.rb:7:in `block (2 levels) in <class:Railtie>'
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config/railtie.rb:4:in `each'
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/rails_env_config-1.1.1/lib/rails_env_config/railtie.rb:4:in `block in <class:Railtie>'
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:49:in `each'
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.5/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/opt/staytus/vendor/bundle/ruby/2.3.0/gems/railties-5.1.5/lib/rails/application.rb:91:in `inherited'
/opt/staytus/config/application.rb:10:in `<module:Staytus>'
/opt/staytus/config/application.rb:9:in `<top (required)>'
/opt/staytus/Rakefile:4:in `require'
/opt/staytus/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)"

Any thoughts as my Staytus is fully broken?

Running with Apache2.2/Ubuntu 16.04

**Comment by bleibson** [comment]
Did you find a solution? I'm trying to bring up Staytus for the first time and seem to be in the same boat.

**Comment by rniedosmialek** [comment]
I have not and was still hoping the dev group would respond with a reason. I am at a point I am look for alternatives.

**Comment by peelman** [comment]
If you're not using `config/enviroment.yml` for anything, remove it or add a `.txt` extension to it.  If you are using it, but can set those variables elsewhere, do that.  Something is broken in the `rails_env_config` it seems and its trying to do an implicit conversion of something in that file (which makes no sense, I have nothing that should be interpreted as FixedNum in mine, but it still throws the error).

**Comment by Natfan** [comment]
Just to note, @peelman's solution worked like a treat for me!

**Comment by ewerton-silva00** [comment]
> If you're not using `config/enviroment.yml` for anything, remove it or add a `.txt` extension to it. If you are using it, but can set those variables elsewhere, do that. Something is broken in the `rails_env_config` it seems and its trying to do an implicit conversion of something in that file (which makes no sense, I have nothing that should be interpreted as FixedNum in mine, but it still throws the error).
> 
> Forget I said that.
> 
> What fixed it for me was adding quotes around the '1' in `FORCE_SSL: "1"`
> 
> ```
> # Staytus environment configuration. Staytus uses
> # unix environment variables to provide its configuration.
> # If your hosting environment does not support setting this
> # easily, you can add them to config/environment.yml and
> # they will be loaded when the application starts.
> 
> # The theme to use
> STAYTUS_THEME: "default"
> 
> # If enabled, the application will allow any username/password
> # combination to login to the admin area.
> STAYTUS_DEMO: "0"
> 
> # Configure an SMTP server for sending messages. If you don't
> # configure an SMTP service, e-mail will be sent using sendmail.
> STAYTUS_SMTP_HOSTNAME: "127.0.0.1"
> STAYTUS_SMTP_PORT: "25"
> STAYTUS_SMTP_USERNAME: "your-username"
> STAYTUS_SMTP_PASSWORD: "your-password"
> 
> # Configure SSL to be forced (ensuring HSTS headers are sent and cookies are all secure)
> FORCE_SSL: "1"
> ```

Tank you, @peelman 

Your tip worked for me.
