### ISSUE TITLE
could not find nokogiri-1.8.2 in any of the sources

### ISSUE THREAD

**Issue by ryan1985r** [adamcooke/staytus#223]
getting the following error when running the following:
/opt/staytus/staytus$ sudo -u staytus bundle exec rake staytus:build

`/home/ubuntu` is not writable.
Bundler will use `/tmp/bundler/home/ubuntu' as your home directory temporarily.
Could not find nokogiri-1.8.2 in any of the sources
Run `bundle install` to install missing gems.

any help much appreciated

**Comment by jeremyjhall** [comment]
Try installing these packages: 

```
sudo apt-get install libxml2-dev
sudo apt-get install libxslt-dev

```
I ran in to the same package issue and the above solved it for me.

**Comment by ryan1985r** [comment]
thanks for your response, got a lot further now but getting the following output when I try to access the web interface with :8787

14:30:17 worker.1        | => [Worker(host:ip-172-26-4-210 pid:31549)] Error while reserving job: Mysql2::Error: Table 'staytus.delayed_jobs
' doesn't exist: SHOW FULL FIELDS FROM `delayed_jobs`

any ideas?

thanks in advance

**Comment by ryan1985r** [comment]
forget that, sorted it now

thanks again
