### ISSUE TITLE
Maintenance Updates not sending emails

### ISSUE THREAD

**Issue by pcooper964** [adamcooke/staytus#231]
Hey All,

We recently setup Staytus and everything is working well, with one exception. When updating an existing entry for Maintenance, the updates do not send out an email. When creating the Maintenance session entry, an email does go out, just not for updates. Updates for Issues work fine. Has anyone seen this before? Any ideas where to look for clues?

Thanks,

Phil

**Comment by skp19** [comment]
Having the same issue. Notifications work for everything except maintenance updates.

**Comment by skp19** [comment]
Duplicate issue

https://github.com/adamcooke/staytus/issues/168

**Comment by danxfisher** [comment]
I submitted a PR with a fix - https://github.com/adamcooke/staytus/pull/251.  You can either use my fork (branch `maint-updates-notify`), make the relatively easy change in the code (check the commit of the PR), or wait for @adamcooke to test, approve, and merge.

**Comment by sprdlik** [comment]
[danxfisher](/danxfisher)'s fix doesn't work for me unfortunatly. It's also not working when I change the column default on notify in maintenance_update table to 1 from 0 like someone else recommended. I still get only an email notification after creating a maintenance but not after updates or any other changes on maintenances. Creating and updating issues works fine. I would assume sending email notifications is a main feature, even for maintenances.
I'm using newest master branch from Jan 04th 2019. Did anybody fixed this issue yet? Any help is welcome.
