### ISSUE TITLE
Anyone tested staytus on other linux than Ubuntu?

### ISSUE THREAD

**Issue by romanr** [adamcooke/staytus#232]
The installation blog article lists Ubuntu. And famous "How to auto start at startup" #157 is specific to Ubuntu.

Has anyone succeeded to run staytus on any other Linux?

**Comment by tiredofit** [comment]
I run it in an Alpine Docker container just fine.. github.com/tiredofit/docker-staytus - Although the developer also provides a Dockerfile to compile that works just as well!

**Comment by mescobar23** [comment]
Just installed on Amazon Linux without any problem

**Comment by matthewalbani** [comment]
use it on centos fine.

**Comment by carlosadean** [comment]
I've been using on CentOS-7 just fine.
