### ISSUE TITLE
https://status.chaturbate.com/ is accessible

### ISSUE THREAD

**Issue by vladossol** [adamcooke/staytus#235]
[an_issue.zip](https://github.com/adamcooke/staytus/files/2138344/an_issue.zip)

Was able to access some strange website https://status.chaturbate.com/ which contains issue data & history, when got an error browsing chaturbate.com

**Comment by Admonstrator** [comment]
That is not an issue because it should work like this. That's why this status page does exist... 😆

**Comment by Paul1961-eng** [comment]
My new WiFi router won't allow me to sign in to chaturbate. What settings do I need to change?
