### ISSUE TITLE
Emails not sending out

### ISSUE THREAD

**Issue by btpuk** [adamcooke/staytus#239]
New to this platform and have tried getting email to go out on a non-standard port to no avail.

in environment.yml I have
STAYTUS_SMTP_HOSTNAME: my.server.com
STAYTUS_SMTP_PORT: '587'

We don't need any authentication as the IP of the Staytus box is on a whitelist. Can anyone advise if I am missing something obvious? Thanks

**Comment by Myrskyvaris** [comment]
How did you resolve this issue?

**Comment by btpuk** [comment]
I think it was using double quotes:
STAYTUS_SMTP_HOSTNAME: "outbound-x.xxxxxxxx.com"
STAYTUS_SMTP_PORT: "25"
