### ISSUE TITLE
I can't install Staytus

### ISSUE THREAD

**Issue by Leon4609** [adamcooke/staytus#24]
I use `bundle install --deployment --without development:test`
and i have 

Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using rake 10.4.2
Using i18n 0.7.0
Installing json 1.8.2 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.2 -r ./siteconf20150727-6500-1ens5ub.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /opt/staytus/vendor/bundle/ruby/2.2.0/gems/json-1.8.2 for inspection.
Results logged to /opt/staytus/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0/json-1.8.2/gem_make.out
An error occurred while installing json (1.8.2), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.2'` succeeds before bundling.

I try `gem install json -v '1.8.2'` and i have : 

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.2 -r ./siteconf20150727-6500-1ens5ub.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /opt/staytus/vendor/bundle/ruby/2.2.0/gems/json-1.8.2 for inspection.
Results logged to /opt/staytus/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0/json-1.8.2/gem_make.out

Log : /opt/staytus/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0/json-1.8.2/gem_make.out

  GNU nano 2.2.6             File: gem_make.out

/usr/bin/ruby2.2 -r ./siteconf20150727-6536-b07d9s.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Lists of files in : /opt/staytus/vendor/bundle/ruby/2.2.0/gems/json-1.8.2

CHANGES                     README.rdoc  ext                lib
COPYING                     Rakefile     *install.rb*         tests
COPYING-json-jruby          TODO         java               tools
GPL                         VERSION      json-java.gemspec
Gemfile                     data         json.gemspec
README-json-jruby.markdown  diagrams     json_pure.gemspec

I try ruby *install.rb*

I try to search and i cannot find answer to my problem.

Please help me,

**Comment by adamcooke** [comment]
This is an issue on your server installing JSON (and subsequently nothing to do with Staytus itself).

https://www.google.co.uk/search?q=json+ruby&oq=json+ruby&aqs=chrome..69i57j69i60.1023j0j1&sourceid=chrome&es_sm=119&ie=UTF-8#q=ruby+json+failed+to+build+gem+native+extension
