### ISSUE TITLE
GDPR Compilance

### ISSUE THREAD

**Issue by ApoRes1337** [adamcooke/staytus#249]
Good day, I have just set up status with me on the server and found that third-party queries are implemented.

Would it perhaps be possible within the meaning of the GDPR to remove them in order to get your data protection law clean substructure?

**Comment by dennym** [comment]
Well which third-party queries are happening? Which one do you think could be violate the GDPR?

**Comment by ApoRes1337** [comment]
Definitely, every third party Request GDPR is relevant, because every operator in Europe has to give more or less account.

Enclosed but like a photo of the third-party requests
![screenshot_6](https://user-images.githubusercontent.com/26686045/45885216-222ef380-bdb6-11e8-83cc-f8e23d30b147.png)

**Comment by dennym** [comment]
Just out of curiosity since I am not that much into GPDR. Isn't it just about personal data is handled/shared/ processed internally and by third parties? 
These requests are just loading fonts, would be the same like just pulling the latest jQuery from a cdn.  In case of loading third party stuff people just have to make sure that the other end is GDPR compliant. Which is obviously the case for google.

Or am I missing something?

**Comment by ApoRes1337** [comment]
In the first place, you're completely right. However, the question is just how well I can guarantee as a site operator that Google also makes no mischief with the data transmitted when querying the fonts or the like. Google is not necessarily a company known for privacy. So who guarantees me and my visitors which data Google collects and which will be processed.

Especially since the queries to third-party providers as well as, for example, the jquery CDN usually increases the load times rather than speeding them up.

Of course it's up to you if you remove the requets, but it would also be another unique feature that you value privacy. Other status pages Scripts or systems unfortunately have the same problem. : /

**Comment by ApoRes1337** [comment]
I also like to hang two tools for you to download Google Fonts or their integration. If you decide to change it.

https://google-webfonts-helper.herokuapp.com/fonts

https://github.com/neverpanic/google-font-download

And a smal Image with a short statement to this topic
![screenshot_7](https://user-images.githubusercontent.com/26686045/45887260-9029e980-bdbb-11e8-9f22-b5016607c488.png)
