### ISSUE TITLE
Using Gmail for SMTP. 

### ISSUE THREAD

**Issue by Myrskyvaris** [adamcooke/staytus#250]
Is it possible to config Staytus to use GMail SMTP? If so, how do I config for SSL port 465?

When I put the following in my config/environment.yml, I always get a 502 Bad Gateway Error.

STAYTUS_SMTP_HOSTNAME: your-smtp-server-hostname
STAYTUS_SMTP_PORT: 465
STAYTUS_SMTP_USERNAME: your-smtp-username
STAYTUS_SMTP_PASSWORD: your-smtp-password

**Comment by Myrskyvaris** [comment]
I see now that as long as environment.yml exists, I get a 502 error.

**Comment by jzielke** [comment]
I have Staytus working under Gmail.  I use port 587 though, have not tried 465 but it should still work.

Also the gmail email address has to be set to less secure, which might be the problem.
[Google Docs](https://support.google.com/accounts/answer/6010255?hl=en)

I also set my environment variables to the same thing as the ruby code seems to check the host environment. Since I am running under Ubuntu, I added them to a profile.d file so they will load on boot. Exported the same settings as below.

STAYTUS_SMTP_HOSTNAME: "smtp.gmail.com"
STAYTUS_SMTP_USERNAME: "<EMAIL Address>"
STAYTUS_SMTP_PASSWORD: "<PASSWORD>"
STAYTUS_SMTP_PORT: "587"
STAYTUS_SMTP_AUTH_MODE: "plain"
STAYTUS_SMTP_STARTTLS: "1"

**Comment by Myrskyvaris** [comment]
Thanks jzielke. I tried that in /etc/profile.d/staytus.sh, and got a "not found" error for each config item in the file. 
Did you have both /opt/staytus/staytus/config/environment.yml and something in /etc/profile.d/?

It seems as soon as I have  /opt/staytus/staytus/config/environment.yml in existence I get a "502 bad gateway error".

**Comment by jzielke** [comment]
staytus.sh should contain and executable

`export STAYTUS_SMTP_HOSTNAME="smtp.gmail.com" `
`export STAYTUS_SMTP_USERNAME="your@email.com"`
`export STAYTUS_SMTP_PASSWORD="youremailpassword"`
`export STAYTUS_SMTP_PORT=587`
`export STAYTUS_SMTP_AUTH_MODE="plain"`
`export STAYTUS_SMTP_STARTTLS=1`


environment.yml should contain - Probably don't need this as the code reads from the environment but I did it anyways.

`STAYTUS_SMTP_HOSTNAME: "smtp.gmail.com"`
`STAYTUS_SMTP_USERNAME: "your@email.com"`
`STAYTUS_SMTP_PASSWORD: "youremailpassword"`
`STAYTUS_SMTP_PORT: "587"`
`STAYTUS_SMTP_AUTH_MODE: "plain"`
`STAYTUS_SMTP_STARTTLS: "1"`



Also don't forget to start Procodile

/etc/systemd/system/staytus.service should contain and registered to start with the system

`[Unit]`
`Description=Procodile-Staytus`
`After=network.target`

`[Service]`
`Type=forking`
`KillMode=none`

`ExecStart=/usr/local/bin/procodile start --root /opt/staytus/staytus/`
`ExecStop=/usr/local/bin/procodile stop -s --wait --root /opt/staytus/staytus/`

`User=staytus`
`Group=staytus`

`[Install]`

`WantedBy=multi-user.target`

**Comment by Myrskyvaris** [comment]
Thanks. 
So I created the status.sh - my original mistake was to use a : and not a =. So after a reboot I received no error message, but still no email sent. 
I recreated environment.yml, and got the same thing: 502 bad gateway.

**Comment by jzielke** [comment]
The only thing I can think of would be a firewall issue or something blocking the complete connection.  Are the correct receive ports open?  That message might be coming from a proxy or something depending on your network not getting the return response. 

Maybe try and send from the shell to see if you can do it that way.  That would take staytus out of the middle. If that works, then it is something in Staytus maybe.

**Comment by Myrskyvaris** [comment]
Staytus works fine until I have environment.yml. If I delete that file and restart, staytus works fine. 

Even with an empty environment.yml I get:
502 Bad Gateway
nginx/1.10.3 (Ubuntu)

In  I see the following in /var/log/nginx/error.log
2018/09/27 12:27:07 [error] 6307#6307: *3 connect() failed (111: Connection refused) while connect i@
2018/09/27 12:28:20 [error] 6307#6307: *6 connect() failed (111: Connection refused) while connect i@

So it looks like nginx is refusing the connection, but only when environment.yml exists.
