### ISSUE TITLE
Setup STMP with just host and port

### ISSUE THREAD

**Issue by tb582** [adamcooke/staytus#262]
I have my environment.yml file but my mail server doesn't need any auth and I've tried every combo of commenting, removing, null to try to get procodile to start but it always throws and error with the yml file. 

So how do I specify just the smtp host and port?

**Comment by Admonstrator** [comment]
I am not a developer at all but I checked the code and would suggest to remove 2 lines in this file:
\config\initializers\smtp.rb

Just remove 
`:user_name              => ENV['STAYTUS_SMTP_USERNAME'],
    :password               => ENV['STAYTUS_SMTP_PASSWORD'],`

Maybe you need to add 1 line to the environment.yml:
`STAYTUS_SMTP_AUTH_MODE: nil`

Please let me know if this helps! :)

**Comment by Admonstrator** [comment]
It's me again:

Maybe you can fix your problem without editing the _smtp.rb
Just add `STAYTUS_SMTP_AUTH_MODE: nil` to your _environment.yml_ and set STAYTUS_SMTP_USERNAME and STAYTUS_SMTP_PASSWORD to ""

**Comment by Admonstrator** [comment]
@tb582 Did it help?

**Comment by tb582** [comment]
sorry for the delay - I was dealing with some onBoot issues... anyway no this didn't work...

```
rake aborted!
TypeError: no implicit conversion of Integer into String
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/rails_env_config-1.1.1/lib/rails_env_config.rb:12:in `[]='
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/rails_env_config-1.1.1/lib/rails_env_config.rb:12:in `block in load'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/rails_env_config-1.1.1/lib/rails_env_config.rb:11:in `each'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/rails_env_config-1.1.1/lib/rails_env_config.rb:11:in `load'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/rails_env_config-1.1.1/lib/rails_env_config/railtie.rb:7:in `block (2 levels) in <class:Railtie>'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/rails_env_config-1.1.1/lib/rails_env_config/railtie.rb:4:in `each'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/rails_env_config-1.1.1/lib/rails_env_config/railtie.rb:4:in `block in <class:Railtie>'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:49:in `each'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/opt/staytus/staytus/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:91:in `inherited'
/opt/staytus/staytus/config/application.rb:10:in `<module:Staytus>'
/opt/staytus/staytus/config/application.rb:9:in `<top (required)>'
/opt/staytus/staytus/Rakefile:4:in `require'
/opt/staytus/staytus/Rakefile:4:in `<top (required)>'
/opt/staytus/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/opt/staytus/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
```

**Comment by tb582** [comment]
I tired multiple different options
commented out the u/p 
left them blank
used blank quotes
nothing worked :(

**Comment by tb582** [comment]
very similar error if I remove the username/password options from the rb file and add the auth mode to the environment.yml

**Comment by tb582** [comment]
Anyone above to help here? looking at the doc's here - 
https://api.rubyonrails.org/classes/ActionMailer/Base.html

I can't find any config issues that would be causing this - I've even tried removing u/p/auth from the rb file but no luck

**Comment by tb582** [comment]
alright we'll I kinda brute forced this one and its working
I removed my environment yaml file and edited the smtp.rb to be:
```
if (:address)
  ActionMailer::Base.delivery_method = :smtp
  ActionMailer::Base.smtp_settings = {
    :address                => 'mailrelay.site.com',
    :port                   => '25',
    :authentication         => 'nil',
    :enable_starttls_auto   => ENV['STAYTUS_SMTP_STARTTLS'] == '1'
 }
```
which is working as expected 👍

**Comment by overdox** [comment]
running unbuntu and I am allso having issues with the smtp config.
Also getting the 
"rake aborted!
TypeError: no implicit conversion of Integer into String"
But I get it if I create the enviroment.yml file and then try to compile the build.
