### ISSUE TITLE
Issue when trying to start

### ISSUE THREAD

**Issue by DamonOnYT** [adamcooke/staytus#271]
root@DDI:~# sudo -u staytus procodile start --dev
Error: Could not find Procfile in //Procfile

please help, i need this back up asap

**Comment by Shimura512** [comment]
Hello @DamonOnYT .

According to the [installation guide](https://atech.blog/atech/install-staytus-tutorial) (**Getting started** and **Give it a test**) you have to be in a folder, where staytus is installed.
By default it is `/opt/staytus/staytus`
So try to  `cd /opt/staytus/staytus` and run the command `sudo -u staytus procodile start --dev`

**Comment by HOD42** [comment]
I found I actually had to change user to staytus and be in that directory (sudo -u staytus wouldn't work). Ubuntu 18.04.
sudo su staytus
cd /opt/staytus/staytus
procodile start --dev
(I do get warnings about "constant Gem::ConfigMap is deprecated" but it appears to work).
