### ISSUE TITLE
Mail config

### ISSUE THREAD

**Issue by kevin-decker** [adamcooke/staytus#290]
Working on getting our instance setup & I'm running into an issue with the mail setup. We have an Exchange environment but utilize IMAP not SMTP - is it possible to use IMAP with this? If so how would we be able to configure the platform to not require a username/password/authentication since we would give this anonymous access to send mail. Thanks for the help in advance!

I, [2019-05-13T12:50:23.859981 #4357]  INFO -- : [519d6ceb-c5d4-41ca-8413-eb19f4830502] Completed 500 Internal Server Error in 5091ms (ActiveRecord: 19.0ms)
F, [2019-05-13T12:50:23.861231 #4357] FATAL -- : [519d6ceb-c5d4-41ca-8413-eb19f4830502]
F, [2019-05-13T12:50:23.861310 #4357] FATAL -- : [519d6ceb-c5d4-41ca-8413-eb19f4830502] Net::SMTPAuthenticationError (504 5.7.4 Unrecognized authentication type
):
F, [2019-05-13T12:50:23.861366 #4357] FATAL -- : [519d6ceb-c5d4-41ca-8413-eb19f4830502]
F, [2019-05-13T12:50:23.861413 #4357] FATAL -- : [519d6ceb-c5d4-41ca-8413-eb19f4830502] lib/staytus/email.rb:40:in `deliver'
[519d6ceb-c5d4-41ca-8413-eb19f4830502] app/models/subscriber.rb:41:in `send_verification_email'
[519d6ceb-c5d4-41ca-8413-eb19f4830502] app/controllers/pages_controller.rb:59:in `subscribe_by_email'
[519d6ceb-c5d4-41ca-8413-eb19f4830502] app/controllers/application_controller.rb:20:in `set_time_zone'

**Comment by tb582** [comment]
Ran into a similar issue - try https://github.com/adamcooke/staytus/issues/262#issuecomment-429914061
