### ISSUE TITLE
 Net::OpenTimeout - debug logs? 

### ISSUE THREAD

**Issue by tb582** [adamcooke/staytus#297]
I'm intermittently not seeing emails being sent out from Staytus... I think it relates to the error below but theres really no further detail into where or what has timed out? 

Is there more debug logs? 

Job Maintenance#send_notifications (id=2) FAILED (0 prior attempts) with Net::OpenTimeout: execution expired

**Comment by tb582** [comment]
Hello ? @adamcooke  ?

**Comment by tb582** [comment]
HELLOOO ?

**Comment by adamcooke** [comment]
Sounds like your SMTP server has issues.

**Comment by tb582** [comment]
> Sounds like your SMTP server has issues.

are there more logs I can enable to get further details from staytus?? I'm grasping at straws to figure it out
