### ISSUE TITLE
We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by philshil** [adamcooke/staytus#30]
Hello,
when i try to upload a cover photo. i receive the error something went wrong.

**Comment by adamcooke** [comment]
You'll need to provide more information. Specifically, the error which you receive which can be found in log/production.log or log/development.log

**Comment by philshil** [comment]
I, [2015-09-21T11:10:34.284028 #3652]  INFO -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59] Processing by Admin::SettingsController#update as HTML
I, [2015-09-21T11:10:34.284163 #3652]  INFO -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"LN92H/DpvUnzKUKTbJZrLfcpJrtKnWfctKOAbiA6WiA6wf1084TF5bNtlJdlu7s8wYxXGpFUy1Add03LMTnsxw==", "return_to"=>"design", "site"=>{"logo_delete"=>"", "cover_image_file"=>#<ActionDispatch::Http::UploadedFile:0x000000060fbd78 @tempfile=#<Tempfile:/tmp/RackMultipart20150921-3652-10l9er.png>, @original_filename="fibre cables.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"site[cover_image_file]\"; filename=\"fibre cables.png\"\r\nContent-Type: image/png\r\n">, "permitted_fields"=>"BAhbBzoObG9nb19maWxlOhVjb3Zlcl9pbWFnZV9maWxl--0d0342cd6212da20bb7165db87876ed7ac72051d"}, "commit"=>"Save Settings"}
D, [2015-09-21T11:10:34.286935 #3652] DEBUG -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59]   [1m[35mAuthie::Session Load (0.5ms)[0m  SELECT  `authie_sessions`.* FROM `authie_sessions` WHERE `authie_sessions`.`active` = 1 AND `authie_sessions`.`token` = '2IV5slQeRz/npX9jxjtneh3RKFHH2Y60ZLYVicKhNsc='  ORDER BY `authie_sessions`.`id` ASC LIMIT 1
D, [2015-09-21T11:10:34.288840 #3652] DEBUG -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59]   [1m[36m (0.1ms)[0m  [1mBEGIN[0m
D, [2015-09-21T11:10:34.306046 #3652] DEBUG -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59]   [1m[35mSQL (15.4ms)[0m  UPDATE `authie_sessions` SET `data` = NULL, `last_activity_at` = '2015-09-21 10:10:34.287467', `last_activity_path` = '/admin/settings', `updated_at` = '2015-09-21 10:10:34.289401' WHERE `authie_sessions`.`id` = 5
D, [2015-09-21T11:10:34.326880 #3652] DEBUG -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59]   [1m[36m (20.3ms)[0m  [1mCOMMIT[0m
D, [2015-09-21T11:10:34.328112 #3652] DEBUG -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59]   [1m[35mSite Load (0.4ms)[0m  SELECT  `sites`.* FROM `sites`  ORDER BY `sites`.`id` ASC LIMIT 1
D, [2015-09-21T11:10:34.328963 #3652] DEBUG -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59]   [1m[36mSite Load (0.3ms)[0m  [1mSELECT  `sites`.* FROM `sites` WHERE `sites`.`id` = 1 LIMIT 1[0m
D, [2015-09-21T11:10:34.329732 #3652] DEBUG -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59]   [1m[35m (0.1ms)[0m  BEGIN
D, [2015-09-21T11:10:35.301801 #3652] DEBUG -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59]   [1m[36m (0.4ms)[0m  [1mSELECT `nifty_attachments`.`id` FROM `nifty_attachments` WHERE `nifty_attachments`.`parent_id` = 1 AND `nifty_attachments`.`parent_type` = 'Site' AND `nifty_attachments`.`role` = 'cover_image'[0m
D, [2015-09-21T11:10:35.373495 #3652] DEBUG -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59]   [1m[35mNifty::Attachments::Attachment Exists (62.1ms)[0m  SELECT  1 AS one FROM `nifty_attachments` WHERE `nifty_attachments`.`token` = BINARY 'f7c62388-6c4c-45fa-b820-a749a72a4dbf' LIMIT 1
D, [2015-09-21T11:10:35.569419 #3652] DEBUG -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59]   [1m[36mSQL (163.6ms)[0m  [1mINSERT INTO `nifty_attachments` (`role`, `parent_id`, `parent_type`, `token`, `data`, `file_name`, `file_type`, `digest`, `created_at`, `updated_at`) VALUES ('cover_image', 1, 'Site', 'f7c62388-6c4c-45fa-b820-a749a72a4dbf', x'89504e470d0a1a0a0000000d49484452000005dc000003e80806000000c40e3ce50000000970485973000016250000162501495224f000000a4f6943435050686f746f73686f70204943432070726f66696c65000078da9d53675453e9163df7def4424b8880944b
this carries on for a long while then after this i get.

49454e44ae426082', 'fibre cables.png', 'image/png', '3369d351fd02ef92f0a783b2498d743c', '2015-09-21 10:10:35.373851', '2015-09-21 10:10:35.373851')
D, [2015-09-21T11:10:35.621108 #3652] DEBUG -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59]   [1m[35m (0.9ms)[0m  ROLLBACK
E, [2015-09-21T11:10:35.621221 #3652] ERROR -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59] Mysql2::Error: MySQL server has gone away: ROLLBACK
I, [2015-09-21T11:10:35.621465 #3652]  INFO -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59] Completed 500 Internal Server Error in 1337ms
F, [2015-09-21T11:10:35.622511 #3652] FATAL -- : [e3188159-d0a0-4378-9e69-58ff3ac53e59] 
ActiveRecord::StatementInvalid (Mysql2::Error: MySQL server has gone away: ROLLBACK):
  app/controllers/admin/settings_controller.rb:13:in `update'
  app/controllers/application_controller.rb:15:in `set_time_zone'


D, [2015-09-21T11:10:36.228789 #2149] DEBUG -- :   [1m[35mSQL (0.3ms)[0m  UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` = '2015-09-21 10:10:36.000000', `delayed_jobs`.`locked_by` = 'host:linux-pjwq pid:2149' WHERE ((run_at <= '2015-09-21 10:10:36.065085' AND (locked_at IS NULL OR locked_at < '2015-09-21 06:10:36.065166') OR locked_by = 'host:linux-pjwq pid:2149') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1

**Comment by adamcooke** [comment]
`Mysql2::Error: MySQL server has gone away`

This is a configuration problem with your MySQL server. Look at increasing the `wait_timeout` configuration option in your mysql configuration.
