### ISSUE TITLE
Make Services sortable

### ISSUE THREAD

**Issue by thomasbg** [adamcooke/staytus#304]
It's very difficult to reorder services (e.g. when names are changed).

**Comment by misterjaytee** [comment]
I've done this by changing some of the code for editing services, however it doesn't check the position against other services (but doesn't break anything if there are two services with the same position). It works and is quicker than doing updates in mysql...

In **app/controllers/admin/services_controller.rb** change the safe_params definition to:
```
  def safe_params
    params.require(:service).permit(:name, :permalink, :description, :status_id, :group_id, :position)
  end
```

In **app/views/admin/services/_form.html.haml**, add a new section wherever you like on the page (I've added it after the Service Group dropdown, and before the buttons - see screenshot):
```
    %dl.fieldSet__field.u-margin
      %dt.fieldSet__label= f.label :position
      %dd.fieldSet__input= f.text_field :position, :class => 'textInput'
```

To validate input, add the following to **app/models/service.rb** (directly below the other validates statements):
`validates :position, numericality: { only_integer: true }`

Then stop the app, rebuild it, then start it again - how you do this may be specific to your implementation, but here's how I do it:
```
procodile stop

# Make sure that there are no web or worker processes running
procodile status

sudo -u staytus bundle exec rake staytus:build staytus:upgrade
sudo -u staytus procodile start

```

Screenshot of how it should look:
![image](https://user-images.githubusercontent.com/5650439/74975118-69436d00-541e-11ea-913e-258ff6541316.png)
