### ISSUE TITLE
To support third-party mail delivery services Mailgun orAmazon SES

### ISSUE THREAD

**Issue by louishot** [adamcooke/staytus#310]
Hi, does have any plan to use third-party mail delivery services in the future Instead of the default SMTP? SMTP looks like it's not multi threaded

**Comment by darkpixel** [comment]
I'm using mailgun to deliver status updates.
In environment.yml:
```
STAYTUS_SMTP_HOSTNAME: 'smtp.mailgun.org'
STAYTUS_SMTP_PORT: '587'
STAYTUS_SMTP_USERNAME: '--redacted--'
STAYTUS_SMTP_PASSWORD: '--redacted--'
FORCE_SSL: '1'
```

**Comment by louishot** [comment]
> I'm using mailgun to deliver status updates.
> In environment.yml:
> 
> ```
> STAYTUS_SMTP_HOSTNAME: 'smtp.mailgun.org'
> STAYTUS_SMTP_PORT: '587'
> STAYTUS_SMTP_USERNAME: '--redacted--'
> STAYTUS_SMTP_PASSWORD: '--redacted--'
> FORCE_SSL: '1'
> ```

Ya! SMTP should be single-threaded
