### ISSUE TITLE
Nginx Error

### ISSUE THREAD

**Issue by thomasthebro1** [adamcooke/staytus#312]
I have just finished getting Staytus setup on port 8787 and it works fine.
After installing Nginx with `sudo apt install nginx` and running the two commands: `sudo curl -o /etc/nginx/sites-available/staytus https://share.adam.ac/files/2017/nginx.staytus.conf` and `sudo ln -fs /etc/nginx/sites-available/staytus /etc/nginx/sites-enabled/default` and finally running `sudo systemctl restart nginx` I get an error in the console which says: **Failed to connect to bus: No such file or directory** - does anyone know why this maybe, I assume it is something to do with the files.

I am running Staytus on a Ubuntu 16.04 server.

**Comment by SOUTHPAWMIKE** [comment]
Had the same issue. I did some research, and the `-o` argument after `curl` needs to instead be a capital `-O`

However, even once this is done, it looks like `https://share.adam.ac/files/2017/nginx.staytus.conf` no longer exists, and can't be downloaded.

**Comment by misterjaytee** [comment]
It will look something like this for a non-secure server (port 80):

```
server {
    listen 0.0.0.0:80 ;
    listen [::]:80 ;
    server_name status.yourdomain.com;

    root /opt/staytus/staytus/public;
    client_max_body_size 50M;

    location /assets {
      add_header Cache-Control max-age=3600;
    }

    location / {
      try_files $uri $uri/index.html $uri.html @puma;
    }

    location @puma {
      proxy_intercept_errors on;
      proxy_set_header X-Real-IP  $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_pass http://127.0.0.1:8787;
    }
}

```

**Comment by maldonadojuan** [comment]
Has anyone found an alternative for this link? https://share.adam.ac/files/2017/nginx.staytus.conf

I didn't have any luck with the suggested Nginx config above.

**Comment by misterjaytee** [comment]
> 
> 
> Has anyone found an alternative for this link? https://share.adam.ac/files/2017/nginx.staytus.conf
> 
> I didn't have any luck with the suggested Nginx config above.

Um, have a look at the post just above yours. That's pretty much taken from the link you were after. Copy and paste it into the file that you are saving your config into. You'll need to replace "status.yourdomain.com" with the address you intend to use (it will need to be a resolvable from your web client.

If you hit any problems, drop a reply in here and I'm sure someone will be happy to help.

**Comment by maldonadojuan** [comment]
> > Has anyone found an alternative for this link? https://share.adam.ac/files/2017/nginx.staytus.conf
> > I didn't have any luck with the suggested Nginx config above.
> 
> Um, have a look at the post just above yours. That's pretty much taken from the link you were after. Copy and paste it into the file that you are saving your config into. You'll need to replace "status.yourdomain.com" with the address you intend to use (it will need to be a resolvable from your web client).
> 
> If you hit any problems, drop a reply in here and I'm sure someone will be happy to help.

Thank you Misterjaytee, I was having some gem bundle issues that were making me think it was the Nginx config. Thank you for reaching out.
