### ISSUE TITLE
SendGrid or Amazon SES support?

### ISSUE THREAD

**Issue by tburazin** [adamcooke/staytus#32]
Any plans for supporting SendGrid or Amazon SES for sending mails?
Sending large quantities of mails from any server requires a bit of work in order to insure they are received properly (not SPAMed) if at all.
Both services have APIs for integration.

**Comment by adamcooke** [comment]
If either of these support sending mail over SMTP, you can just configure them using the `STAYTUS_SMTP_HOSTNAME`, `STAYTUS_SMTP_USERNAME` and `STAYTUS_SMTP_PASSWORD` environment variables.
