### ISSUE TITLE
"More Info" indicator

### ISSUE THREAD

**Issue by darkpixel** [adamcooke/staytus#320]
![Screenshot from 2020-04-30 19-17-09](https://user-images.githubusercontent.com/158380/80776463-4bc60a00-8b17-11ea-8fe9-0b78403dcfd6.png)

There really needs to be a 'more info' button on the status items at the top of the page.

I use Staytus to indicate problems at various offices.  Earlier today our main office was having problems, and in the details I listed "This is affecting our reporting portal".

For the next hour users turned in tickets about it.  When I replied and closed the ticket with "Please remember to check the status page.  We are aware of the issue, please see https://status.....".

Finally a manager replied to the ticket and said "I don't see anything wrong with our office".

It dawned on me that they are seeing the title on the main page (i.e. "Comcast Outage at the Main Office") and that's it.

I ran a quick search of the web logs.  In 6 months, the only things that have seen the 'details' page are search engine bots indexing the site, and the staff in the IT building.

I called the user and asked her to show me.  She went to the home page and said "See?  There's only an outage affecting the main office."

I asked her to click on it and her reply was "Oh, I can click on it?"

Any way we can add a 'more info' button to statuses that show up at the top of the page?

**Comment by misterjaytee** [comment]
Hi,

You should just be able to click on the status blocks at the top of the page - so where you have the blue box which says "Network Connectivity Issues", you can click on that to get to the additional info you need.

**Comment by misterjaytee** [comment]
Useful clarification, and I think you could be right there. However, I'm not sure of how the UI design would be best here. Maybe just some simple text in the box that says "Click for more info".

P.S. I haven't seen the author of this project around here for a while. However, I think this is a useful and easy change. I'll post back when I've done the change to my own install.

**Comment by misterjaytee** [comment]
It isn't pretty, but this is what I've come up with as a quick change:
![image](https://user-images.githubusercontent.com/5650439/83324323-6e555b00-a25c-11ea-97c9-26eb5e56d8e6.png)

The file to change is content/themes/default/views/pages/index.html.erb. I've made the change in my fork here (no need to rebuild):
https://github.com/misterjaytee/staytus/blob/master/content/themes/default/views/pages/index.html.erb

Please note in my version I have dropped the Subscribe link - if you still want this then simply remove the "<% ignore do %>" and "<% end %>" on Line 10.

**Comment by darkpixel** [comment]
Works for me.  The copy/paste saved me a few minutes of reading the HTML and figuring out where to stick stuff. :)  Thanks!

**Comment by darkpixel** [comment]
I would love to see a "More info" link in a future release.
