### ISSUE TITLE
remove subscribers

### ISSUE THREAD

**Issue by alexxxPopa** [adamcooke/staytus#328]
Is it possible to remove the subscirbers option, even if it's only from the presentation layer?

**Comment by mwstamant** [comment]
You can hide the subscribe button using CSS:

Open `<staytusroot>/content/themes/default/assets/stylesheets/default/site_header.scss`

search for the CSS class `.siteHeader__subscribe` and append the following CSS property and value: `visibility: hidden;`

**Comment by MrPadingy** [comment]
I don't know if this is a new feature, but it's possible to remove the subscriber button from the public site by navigating to /admin/settings/general and unticking the "Allow visitors to subscribe to your status site?" box.
