### ISSUE TITLE
Public Homepage

### ISSUE THREAD

**Issue by cajepson13** [adamcooke/staytus#329]
I want to add an admin login link to the public page to make it easier, where is the index.html.haml file for the Public Homepage. I'm probably just missing it, but I seem to be able to find everything but this.

**Comment by cajepson13** [comment]
I would also like to change the contact us from a mail to link to a link to our helpdesk page.

**Comment by adamcooke** [comment]
I'm afraid we can't help with specific issues with implementation here. GitHub issues should be reserved for bug reporting at this stage.
