### ISSUE TITLE
Show exact time stamps on incidents

### ISSUE THREAD

**Issue by MrPadingy** [adamcooke/staytus#335]
Rather than having "Posted about 20 hours ago" have an option to use an exact time stamp to show "Posted at 15:30 - 03/11/2020" (Format as per timezone etc).

**Comment by nrukavkov** [comment]
@MrPadingy today i've done some changes on issue page. You can download docker image appulate/staytus:latest or get sources and build it from stable branch https://github.com/appulate/staytus/tree/stable

**Comment by MrPadingy** [comment]
Thanks for your work @nrukavkov that allowed me to find the file I needed and make the changes that I wanted.

For anyone else with this query. Locate the following file, issue.html.erb. (opt/staytus/staytus/content/themes/default/views/pages/issue.html.erb)

Modify the below lines:
Line 18
`<p class='issueDetail__date'>Opened on <%= @issue.created_at.strftime("%A #{@issue.created_at.day.ordinalize} %B %Y") %>, last updated <%= time_tag @issue.updated_at %></p>`
↓ 
`<p class='issueDetail__date'>Opened on <%= @issue.created_at.strftime("%A #{@issue.created_at.day.ordinalize} %B %Y at %H:%M") %>. Last updated <%= time_tag @issue.updated_at %></p>`


Line 29
`Posted <%= time_tag update.created_at%>`
↓
 `Posted at <%= update.created_at.strftime("%H:%M - %d/%m/%Y") %>`

This displays updates like:
![image](https://user-images.githubusercontent.com/40717029/100391268-cd890200-302a-11eb-91fb-74751fb3bec1.png)

Rather than the default:
![image](https://user-images.githubusercontent.com/40717029/100391333-fb6e4680-302a-11eb-87c7-516e83cc91a0.png)
