### ISSUE TITLE
Allow better formatting in issues/maintenances

### ISSUE THREAD

**Issue by ibot3** [adamcooke/staytus#350]
Currently, not even new lines are possible in maintenance/issue descriptions. At least that would be helpful. 

Additional Markdown support would be even better, also for the page description shown in the header.

**Comment by SuperSajuuk** [comment]
@adamcooke This is a useful feature and would make it easier to do a "postmortem" style of closing update on any incidents with severe impact.

**Comment by flaviohcardoso** [comment]
+1 My vote is the markdown..

**Comment by adamcooke** [comment]
Will be add

**Comment by SuperSajuuk** [comment]
Why was this closed? It's a useful feature to have and the open PR was never merged. 😕

**Comment by adamcooke** [comment]
The PR will be merged.
