### ISSUE TITLE
Docker update

### ISSUE THREAD

**Issue by TripleHHH28** [adamcooke/staytus#354]
Hello,

How am I able to update to the latest staytus program? I currently have 1.1.0 and want to update it to 1.3.1 or whatever the latest version is. I have tried through the normal ways to update but it is the same 1.1.0 version over and over.

Any hints? I can't for the life of me find anything on how to update it.

I don't think this is working as expected but I could be wrong.

**Comment by darkpixel** [comment]
I have a newer docker package built for my own use.  It might help you.
It's currently 1 commit behind, but I was about to update it and remove my 'Uglifier patch'.

https://github.com/darkpixel/staytus-docker/

**Comment by TripleHHH28** [comment]
> I have a newer docker package built for my own use. It might help you.
> It's currently 1 commit behind, but I was about to update it and remove my 'Uglifier patch'.
> 
> https://github.com/darkpixel/staytus-docker/

Thanks for this. I tried to do a pull request but it keeps saying I need permission to do it. "Access denied" "Request to the resource is denied"

**Comment by darkpixel** [comment]
Hmm...I'm not sure why ```docker login``` wouldn't work against github.  Maybe an expired token.  Take a look here: https://docs.github.com/en/packages/guides/configuring-docker-for-use-with-github-packages
