### ISSUE TITLE
Office 365 SMTP Settings

### ISSUE THREAD

**Issue by athornfam2** [adamcooke/staytus#356]
I'm having some trouble adding either SMTP relay or a licensed user to the SMTP settings. First off, I don't have an environment.yml file to edit but I have an example.environment.yml file. 

![environment example yml](https://user-images.githubusercontent.com/74559383/110121583-92663f80-7d8c-11eb-9dd2-80f4ee52ba77.png)

I've also modified smtp.rb with no success either

![smtp rb](https://user-images.githubusercontent.com/74559383/110121729-c0e41a80-7d8c-11eb-9ee7-83f014fe59e8.png)

For both SMTP changes I've restarted the procodile too.

When I perform a foreman start under the Staytus directory it says that SMTP hasn't been configured.

![foreman start](https://user-images.githubusercontent.com/74559383/110122054-20dac100-7d8d-11eb-808b-5fdd3ac5a799.png)

**Comment by Josh-Sul** [comment]
You must create your own environment.yml file and edit the settings in there.

Type `cp example.environment.yml environment.yml` and then `nano environment.yml` to edit it and place the settings within that file.

Let me know if you get stuck.
