### ISSUE TITLE
Add a config entry to put google analytics key

### ISSUE THREAD

**Issue by GhaziTriki** [adamcooke/staytus#358]

**Comment by GhaziTriki** [comment]
Hi @adamcooke, any reason for closing this ticket?

**Comment by adamcooke** [comment]
Sorry. I thought I'd written one! I don't really plan on adding this directly because it also, for many, requires a bunch of extra work to handle cookie acceptance which I didn't want to handle. 

Templates can be edited to add this though on a per install basis.

**Comment by GhaziTriki** [comment]
Thanks for the tip @adamcooke, a custom template will do its job.
