### ISSUE TITLE
Add validation on description length

### ISSUE THREAD

**Issue by anubhavranjan** [adamcooke/staytus#36]
Hi,

I have tried installing this using the Viaduct App.
However, on the setup page, after entering the details, all I get is this error message:

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

Log:
122.171.176.85 - - [30/Oct/2015:21:58:44 +0000] "POST /500 HTTP/1.1" 500 1477 0.2219
122.171.176.85 - - [30/Oct/2015:22:01:18 +0000] "POST /500 HTTP/1.1" 500 1477 0.0214

**Comment by anubhavranjan** [comment]
It seems the issue happens when the Description is filled with more number of characters. Can you please state the limit for Description?

**Comment by andrewpuch** [comment]
I get the same issue...is it possible either open up that field to be longer or provide a simple error message your field is too long?
