### ISSUE TITLE
Staytus does not send emails to all subscribers

### ISSUE THREAD

**Issue by TLucasJr** [adamcooke/staytus#362]
We have been using Staytus for about two years now with no issues. We recently discovered emails are not being sent to all subscribers. We tried removing them and having them subscribe again. It worked for a few emails and then stops sending again. 
I have performed a message trace and noticed the emails only send to 4 users out of 300. 
Any ideas as to why this is happening?

**Comment by adamcooke** [comment]
Users do need to confirm their email address when they subscribe. If they don't do this, they don't receive the email. You could check the subscribers table and ensure they all have verification timestamps.
