### ISSUE TITLE
Any chance for updated installation instructions?

### ISSUE THREAD

**Issue by jhnmonsun** [adamcooke/staytus#364]
Hello,

I tried reaching out to you on Twitter as well. Hoping you can help with an updated installation instruction :).

The installation procedure fails when adding the Ruby dependencies, as some of the sub libraries no longer exists. I believe mimemagic was removed and is no longer needed in v. 6 (some background here: https://github.com/mimemagicrb/mimemagic/issues/98). Anyway I cannot install the Staytus software on my new server. It's a shame, because the software works really great once running :).

**Comment by adamcooke** [comment]
I am planning on a change to these quite soon to improve the experience for everyone. Soon, Staytus will be distributed and supported exclusively using containers rather than requiring any of the complex bits we currently require.
