### ISSUE TITLE
Feature: subscribe per service

### ISSUE THREAD

**Issue by jobauer** [adamcooke/staytus#37]
When someone is registering for email alerts, he gets a selection of services and can select, which services he is interested in.
reason: API users are not interested in web interface down and vice versa.

Current workaround is to host status pages for all different services, which adds up.

**Comment by sighup** [comment]
I would also like to see per-service notification subscriptions implemented.

**Comment by adamcooke** [comment]
I don't have any plans to add this myself as Staytus is designed to be simple.
