### ISSUE TITLE
running with apache

### ISSUE THREAD

**Issue by srikanth88infy** [adamcooke/staytus#41]
Hi,

I am relatively new to ruby island and was wondering how to run staytus with Apache. What would be the document root for the configuring apache server?

**Comment by andrewpuch** [comment]
What I did was edit 

```
nano config/boot.rb 

:Host => '127.0.0.1'
```

Then my apache config to proxy pass to port 5000

````
ProxyRequests off

<Proxy *>
    Order deny,allow
    Allow from all
</Proxy>

<Location />
    ProxyPass http://localhost:5000/
    ProxyPassReverse http://localhost:5000/
</Location>
```

See if that works! Good luck!

**Comment by srikanth88infy** [comment]
@andrewpuch  thanks a ton man! :+1:

**Comment by andrewpuch** [comment]
Yep no problem!! Cool thing I do too for anyone who uses nodejs is actually run this using PM2. And I have my apache config as a proxy pass to it.

I create a file called `staytus.sh` with

```
#!/bin/bash

bundle exec foreman start
```

Then to start it I run

```
pm2 start staytus.sh --interpreter bash --name STAYTUS
```
