### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by MaikelVE** [adamcooke/staytus#49]
When i typ in "mysql$ CREATE DATABASE `staytus` CHARSET utf8 COLLATE utf8_unicode_ci;
mysql$ GRANT ALL ON staytus.* TO `staytus`@`localhost` IDENTIFIED BY "a_secure_password";" and i click go, then an error apears with the following:

"
Error
SQL query:

mysql$ CREATE DATABASE  `staytus` CHARSET utf8 COLLATE utf8_unicode_ci;

MySQL said: 

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'mysql$ CREATE DATABASE `staytus` CHARSET utf8 COLLATE utf8_unicode_ci' at line 1 
"

**Comment by adamcooke** [comment]
You can try escaping the charset and collation with backticks.

If you're struggling to create the database and can't debug it, you may struggle to actually complete the rest of the installation
