### ISSUE TITLE
Add groups to organize services

### ISSUE THREAD

**Issue by VA6DAH** [adamcooke/staytus#5]
Hi,

Enhancement request here.

Like CachetHQ, it would be great to be able to sort services into groups, especially in my situation where I will being doing a status page for different locations.

Example:

New York (Group with services below.)
-- Server Alpha .......... Operational
-- Server Bravo .......... Degraded IO

California
-- Server Alpha .......... Operational
-- Server Bravo .......... Degraded IO

Cheers

**Comment by srikanth88infy** [comment]
wondering if anyone has some status/inputs on this.

**Comment by adamcooke** [comment]
This would be a nice idea. I've added it as a potential future feature

**Comment by pgnuta** [comment]
+1 for this idea.  I'm building a nagios event handler to update Staytus services via the API and it would be great if i could collapse services down into logical groups so that my many hundreds of services didn't make you scroll for years.

**Comment by tilsammans** [comment]
Hi @adamcooke could you tell us if Staytus has been abandoned? If so that's fine, but I'll use the fork @novotarq since it has this feature.

**Comment by adamcooke** [comment]
It certainly hasn't been abandoned. I'll take a look at getting this merged in the next few days :)

**Comment by tilsammans** [comment]
Ah cool! cheers 😄
