### ISSUE TITLE
Set up automated build on Docker Hub

### ISSUE THREAD

**Issue by astopy** [adamcooke/staytus#52]
It'd be nice if the repo on the Docker Hub was an automated build (with a [repository link](https://docs.docker.com/docker-hub/builds/#repository-links) to the ruby repo), so that the image would be kept up to date automatically (especially for example if the base ruby image receives security updates).

**Comment by adamcooke** [comment]
I'm afraid I have very little experience with Docker so I'm not really in a position to be able to spend too much time on this. I don't really have time to maintain a docker version of this. It would be great is someone else would take over this.

**Comment by astopy** [comment]
@adamcooke I'd be very happy to maintain the Docker side of things here. Regarding your comment in #50 about where to keep the config, it would certainly be possible to keep the Dockerfile and any Docker-specific scripts in a separate repo, though obviously in that case it would probably be best to also create a staytus organisation here on GitHub to keep everything together.
