### ISSUE TITLE
Multi-Customer Use

### ISSUE THREAD

**Issue by johnmac77** [adamcooke/staytus#55]
Would it be possible to have different status pages from different customers and then only see the status's for their servers / services.

What I mean by this is I have lots of customers that share suppliers (e.g internet providers) if I tag all the customers with that supplier in the admin portal somehow then when I say there is a problem with that supplier it could alert all the customers with that suppler and update their status's pages.

**Comment by ubiquitousthey** [comment]
I have a similar use case.  We have multiple tenants and would like to give each his own status page after logging in.  We are going to try staytus out and, if it works well internally, I'll fork it and add this feature.

**Comment by jbrooksuk** [comment]
I don't think that @adamcooke is going to make Staytus into a SaaS app for you to run...

**Comment by jrbeilke** [comment]
+1 for some sort of hierarchy for services in staytus. Even better if visibility of certain services can be hidden behind authentication.

**Comment by adamcooke** [comment]
I'm afraid I don't have any plans to add support for anything like this at the moment. Staytus is designed to solve a specific simple purpose. This doesn't really fit with my vision.
