### ISSUE TITLE
Translation in french

### ISSUE THREAD

**Issue by nicolasgl** [adamcooke/staytus#56]
Is it possible to translate in french ?

Have you already make language files ?

**Comment by adamcooke** [comment]
I'm afraid I have no immediate plans to add any i18n to Staytus at the moment.

**Comment by jbrooksuk** [comment]
FWIW, [Cachet](https://cachethq.io) is multi-lingual.

**Comment by adamcooke** [comment]
Use Cachet then :smile:

**Comment by jbrooksuk** [comment]
I submitted the comment too early, my bad.
