### ISSUE TITLE
How do i change it to run on other port then 5000

### ISSUE THREAD

**Issue by haybeseret** [adamcooke/staytus#6]
hi,

I am kind of new to Ruby, how do i change it to run on other port then port 5000, or to make it work with nginx/apache ?

**Comment by prolix21** [comment]
bundle exec foreman start -p 80

that will start it on port 80

**Comment by haybeseret** [comment]
Thanks mate.

בתאריך יום ה׳, 4 ביוני 2015 ב-02:49 מאת prolix21 <notifications@github.com>:
