### ISSUE TITLE
SQL Issue

### ISSUE THREAD

**Issue by AlexLamond** [adamcooke/staytus#63]
Set up staytus and get the following error after I run <code>bundle exec foreman start</code>
 
<code>Error while reserving job: Mysql2::Error: Table 'staytus.delayed_jobs' doesn't exist: SHOW FULL FIELDS FROM `delayed_jobs`</code>

I am able to access the domain where it is set up but it simply displays an error saying something went wrong

**Comment by adamcooke** [comment]
Sounds like you haven't run the setup/install commands. Refer to the documentation to ensure your database is set up correctly.
