### ISSUE TITLE
Run Ruby server in background

### ISSUE THREAD

**Issue by philshil** [adamcooke/staytus#65]
Hello,
is there a way to make the ruby server run in the background as a service?

**Comment by pgnuta** [comment]
You will probably want to look at installing phusion passenger, they the ruby server will run as an apache module.  Here is what i did on Centos 6:

`
yum install httpd curl-devel httpd-devel
gem install passenger
passenger-install-apache2-module

vi /etc/httpd/conf/httpd.conf
`
Paste in 

`
LoadModule passenger_module /usr/local/rvm/gems/ruby-2.2.0/gems/passenger-5.0.28/buildout/apache2/mod_passenger.so
<IfModule mod_passenger.c>
	PassengerRoot /usr/local/rvm/gems/ruby-2.2.0/gems/passenger-5.0.28
	PassengerDefaultRuby /usr/local/rvm/gems/ruby-2.2.0/wrappers/ruby
</IfModule>
`

Finally create a new VirtualHost entry in /etc/httpd/conf.d/

`
<VirtualHost *:80>
  DocumentRoot /opt/staytus/public
  ServerName  [put your server name here]
  CustomLog /opt/staytus/log/access_log combined
  ErrorLog /opt/staytus/log/error_log
  <Directory "/opt/staytus/public">
    AllowOverride All
    Options -MultiViews
  </Directory>
</VirtualHost>
`
