### ISSUE TITLE
Is Ping response possible?

### ISSUE THREAD

**Issue by cmpsoares91** [adamcooke/staytus#69]

**Comment by cmpsoares91** [comment]
Hello,

I would like to know if an automated ping response monitor is already implemented? 
In the firm of a response time graph, table or something like it?

Best regards, 
Carlos Soares.

**Comment by cmpsoares91** [comment]
Sorry just read it in the road map. Is there any expected date for it?

**Comment by adamcooke** [comment]
There's no ETA for this at the moment I'm afraid.
