### ISSUE TITLE
Relative links

### ISSUE THREAD

**Issue by tremblane** [adamcooke/staytus#76]
The links are showing up as absolute instead of relative. I've got it running in docker, proxied behind apache, via **foo.com/staytus**. The "/history" link for example takes me to **foo.com/history**. Instead, I'd want it to be "history", taking me to **foo.com/staytus/history**.

**Comment by adamcooke** [comment]
I'm afraid I have no plans to try and support running staytus at anything other than the root of a domain. It's such a small use-case (and not one I've got) it just isn't worth the time to support it. Sorry.
