### ISSUE TITLE
Question regarding changing config options for puma

### ISSUE THREAD

**Issue by rednexus** [adamcooke/staytus#77]
Hi,

I'm playing around setting up the status page based on your code and instructions.  I was wondering if you knew how I could potentiall change the port number it listens on, currently 5000, and also how I might be able to support SSL for the site.  I feel I have gone through every config but I cant quite pick up where the options are coming from.  I have it all up and running using its default settings.  I haven't used docker by the way.  Any help would be appreciated.

Mark

**Comment by pgnuta** [comment]
Here's a reply I wrote which basically answers the question, SSL essentially will work with a relevant apache SSL config which I'll leave as an exercise for the reader.

https://github.com/adamcooke/staytus/issues/65

**Comment by rednexus** [comment]
Thanks will give that go. Much appreciated.

**Comment by rednexus** [comment]
That worked a treat by the way.  Thanks.
