### ISSUE TITLE
Collapsable service groups

### ISSUE THREAD

**Issue by pgnuta** [adamcooke/staytus#80]
Can we make it so that the service groups collapse and when collapsed display an overall service status for the whole group?  Clicking the expanding icon for the group would, of course, show all services in the group and each service's status individually.  It would make it much easier to maintain large lists of services while still having the status page a manageable size for viewing.

It would also be good if we could have a filter in the admin page to limit the services displayed to the service group selected.

Lastly, the drag-reordering of services has already been discussed elsewhere but this would solve the last of my issues if implemented.  I think that drag-reordering would work quite well with the service-group filtering mentioned above too.

**Comment by benjisoft** [comment]
+1 to this!

**Comment by rsgfernandes** [comment]
+1

**Comment by joaojjmb** [comment]
+1 !

**Comment by omtr** [comment]
+1

**Comment by jbrooksuk** [comment]
I just want to pop in to say that [Cachet](https://github.com/CachetHQ/Cachet) has this 😉

**Comment by hjone72** [comment]
@jbrooksuk, I would be on board with cachet if you could update issues. As far as I could tell from the demo you can only create new issues. Is this a feature you guys are going to implement?

**Comment by jbrooksuk** [comment]
v2.4 already solves this. It's still a dev build at the moment but it's already in 😄

**Comment by hjone72** [comment]
@jbrooksuk, is there a demo I could test of this? I'm in the middle of swapping systems  so I don't have available resources to set a personal demo up.

**Comment by jbrooksuk** [comment]
I'll set a v2.4 demo up tonight, if that's okay?

**Comment by hjone72** [comment]
Yes please!

**Comment by adamcooke** [comment]
Feel free to take this chat somewhere else!
