### ISSUE TITLE
Change webserver port

### ISSUE THREAD

**Issue by benjisoft** [adamcooke/staytus#81]
This may seem a little bit of a stupid question, but I can't for the life of me find out how to change the port staytus runs on.

**Comment by dvinciguerra** [comment]
Hi benjisoft,

You can use Rakefile to configure port number adding this snippet of code:

task :server do
  `bundle exec rails s -p 8080`
end

**Comment by adamcooke** [comment]
Don't do that. You'll end up with more issues than it solves. 

There is is no official way to change this port number at present. Use a web proxy server to proxy requests from your public port to your internal one.
