### ISSUE TITLE
Master branch breaks homepage

### ISSUE THREAD

**Issue by benjisoft** [adamcooke/staytus#82]
After upgrading to the master branch the front page changed to: 
![image](https://cloud.githubusercontent.com/assets/8136412/16902105/d2254452-4c4c-11e6-88ef-96522de7040e.png) some of the admin area is availiable. However, some of it displays this page as well.

**Comment by adamcooke** [comment]
Please provide the appropriate extract from your log file so this can be investigated. You can find it in `log/production.log`

**Comment by benjisoft** [comment]
Apologies, I forgot to run `bundle exec rake staytus:build staytus:upgrade` to update the database. All is fixed now
