### ISSUE TITLE
Email Generation

### ISSUE THREAD

**Issue by wahyzcrak** [adamcooke/staytus#83]
I am curious how the emails are generated for the notifications, for instance, do they go into a queue in the database that is cleared out in a queue fashion by some other process, or are the messages just kind of generated as a blob and sent out?

Mainly I am wondering what kind of capacity the subscription feature has for generating emails to a large number of recipients? Say 50k for an example

**Comment by adamcooke** [comment]
E-mails are sent out in a background worker process rather than in the foreground. We can scale this as needed, I'm sure.
