### ISSUE TITLE
Staytus custom theme

### ISSUE THREAD

**Issue by ianmoone** [adamcooke/staytus#84]
Hello,
I've managed to add a theme to staytus and declare it in conf file, but it doesn't seems to display my css changes on the page.
Is there something special to do in order to regenerate the stylesheets ?
Thank you

**Comment by bpruett** [comment]
Were you able to figure out how to get the system to rebuild the css files?
I have them created as well but cannot find a rake job to regenerate the assets.

**Comment by bpruett** [comment]
I solved the problem and thought I would mention the solution here so that others will find it. 

Just a standard `rake assets:precompile` from the base directory will take care of compiling the SCSS and adding your changes to the pipeline.

**Comment by ianmoone** [comment]
Thanks @bpruett but I must misunderstand something here ... I thought all I had to do was to duplicate the default theme and make my changes, but doesn't seems to work like that.
Is there anything else to do with these files to get a custom theme ?

**Comment by Mauredo** [comment]
I'm having the same issue right now. Every change I do in the service_list.scss does not show in the website. Even if I try to reboot the website.

Doing what @bpruett has said fixed the problem.

My question is now: is it really necessary to do this every time? Is there a way to add this execution to the site boot?

**Comment by Nicholi** [comment]
What is the "base directory" you run `rake assets:precompile` from?

Running from the staytus checked out directory doesn't build any new assets. I have specified the new theme name in environment.yml.
> $ rake assets:precompile
> (in /opt/staytus/staytus)
> => Loaded local environment variables from /opt/staytus/staytus/config/environment.yml

If anyone can help out, here are the basic steps I've followed. I've copied the default theme directory in its entirety (cp -R default newtheme). Made the few changes I wanted to. Specified my new theme under STAYTUS_THEME: 'newtheme' in environment.yml. Finally run bundle exec rake staytus:build staytus:upgrade.

After starting up staytus again I just get the standard error page:

> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

**Comment by adamcooke** [comment]
If you copy a new theme, you also need do some renaming within the theme folder itself. This isn't very clear and could well be improved.

* Rename the `default` directories in assets/images, assets/stylesheets & assets/javascripts to match the name of your new theme
* Rename the layout file from `default.html.haml` to `[newthemename].html.haml` in views/layouts
* Update references in the layout file (in views/layouts) to include links to your newly named CSS & javascript files. 

You'd also be best running the application in `development` mode so that you see errors. By default, it runs in production.

```
RAILS_ENV=development procodile start --foreground
```

**Comment by maldonadojuan** [comment]
Not sure if this will help or not, but I needed to make changes to some CSS files and the changes were not loading for me.
What ended up working was running the following commands treating it as if it were an upgrade:
`cd /opt/staytus/staytus`
`sudo -u staytus procodile stop -s --wait`
`sudo -u staytus bundle`
`sudo -u staytus bundle exec rake staytus:build staytus:upgrade`
`sudo -u staytus procodile start`

Once this set of commands were run, the changes in my CSS files were reflected on page refresh.
