### ISSUE TITLE
When to use Staytus over Cachet?

### ISSUE THREAD

**Issue by yonas** [adamcooke/staytus#96]
Hi, I was wondering why I might want to use Staytus instead of [Cachet](https://github.com/CachetHQ/Cachet)?

**Comment by jbrooksuk** [comment]
Always 😉 

I'd say that Cachet is more feature complete than Staytus. Staytus is very nice and does some things better than Cachet.

We have:

- Metrics
- Translations
- Full JSON API
- Component Groups
- 2FA
- An active community

**Disclosure: I'm the lead developer of Cachet.**

**Comment by adamcooke** [comment]
Never. It's written in PHP ;)


Adam Cooke
Managing Director

tel. 01202 912 446 email. adam@atech.media<mailto:adam@atech.media> web. https://atech.media

This e-mail has been sent by aTech Media Limited (or one of its assoicated group companys, Dial 9 Communications Limited or Viaduct Hosting Limited). Its contents are confidential therefore if you have received this message in error, we would appreciate it if you could let us know and delete the message. aTech Media Limited is a UK limited company, registration number 5523199. Dial 9 Communications Limited is a UK limited company, registration number 7740921. Viaduct Hosting Limited is a UK limited company, registration number 8514362. All companies are registered at Unit 9 Winchester Place, North Street, Poole, Dorset, BH15 1NX.

**Comment by jbrooksuk** [comment]
> Never. It's written in PHP 😉

Well played Mr. Cooke.

**Comment by yonas** [comment]
Thanks! I couldn't ask for a more qualified people to answer my question :)

**Comment by adamcooke** [comment]
Changed the title of the ticket to make James's and my reply make sense!

**Comment by jbrooksuk** [comment]
:)
