### ISSUE TITLE
{{issue.user}} and {{update.user}} do not work.

### ISSUE THREAD

**Issue by LKHetzel** [adamcooke/staytus#97]
When using the variables {{issue.user}} and {{update.user}} in the email templates, they do not translate to the user that created/updated the issue. Is this a known bug or is there a different variable to show the username in the template?

> Posted at: 2016-08-26 18:56:13 UTC
Affected services Test Service
**Created by: {{issue.user}}**

**Comment by adamcooke** [comment]
It should be entered as `{{issue.user.name}}` or `{{update.user.name}}`.
