### ISSUE TITLE
[Suggestion] How about a Slack or Gitter group ?

### ISSUE THREAD

**Issue by leovarmak** [adamcooke/staytus#99]
I feel this way a lot of us can help each other

**Comment by adamcooke** [comment]
While I don't really like the idea of Slack for Open Source projects, there is an IRC channel on Freenode `#staytus`. I'm usually around in there.

**Comment by leovarmak** [comment]
Haha. Well Slack looks cool. IRC is way too old man. How about we use [Raspchat](https://beta.raspchat.com/) if I can get in configured on a server ?

**Comment by adamcooke** [comment]
It might be old but it does the job pretty well. I have an existing IRC client open. I'll never be there if I have to open another. This article explains my feelings about it :)

http://sircmpwn.github.io/2015/11/01/Please-stop-using-slack.html


Adam Cooke
Managing Director

tel. 01202 912 446 email. adam@atech.media<mailto:adam@atech.media> web. https://atech.media

This e-mail has been sent by aTech Media Limited (or one of its assoicated group companys, Dial 9 Communications Limited or Viaduct Hosting Limited). Its contents are confidential therefore if you have received this message in error, we would appreciate it if you could let us know and delete the message. aTech Media Limited is a UK limited company, registration number 5523199. Dial 9 Communications Limited is a UK limited company, registration number 7740921. Viaduct Hosting Limited is a UK limited company, registration number 8514362. All companies are registered at Unit 9 Winchester Place, North Street, Poole, Dorset, BH15 1NX.

**Comment by leovarmak** [comment]
@maxpert
